//! Nudge Python codegen (design §14 contract, v1.3) — day 4–6 scope.
//!
//! Lowers the AST to a single deterministic Python file importing only
//! stdlib + `nudge_runtime`:
//!   type alias  → `Name = rt.schema({...})` JSON-Schema literal (records are
//!                 plain dicts validated at runtime; dataclasses post-MVP)
//!   tool        → `def name(...): return rt.tool_stub("name")` (real MCP
//!                 wiring lands day 8–10)
//!   llm call    → `rt.llm_call(prompt=…, schema=rt.schema(…), model=…, …)`
//!   test block  → comment (the `nudge test` runner lands day 9–10)
//!
//! Determinism (design §14 rule d): identical AST ⇒ byte-identical output.

use crate::ast::*;
use std::collections::HashSet;

pub fn emit(items: &[Item]) -> String {
    let aliases: HashSet<String> = items
        .iter()
        .filter_map(|i| match i {
            Item::TypeAlias { name, .. } => Some(name.clone()),
            _ => None,
        })
        .collect();

    let mut out = String::new();
    out.push_str("\"\"\"Generated by nudgec 0.1.0 — do not edit.\"\"\"\nimport nudge_runtime as rt\n");
    let mut has_main = false;
    for item in items {
        out.push_str("\n\n");
        match item {
            Item::TypeAlias { name, ty } => {
                out.push_str(&format!("{name} = rt.schema({})", schema_py(ty, &aliases)));
            }
            Item::Fn { name, params, effects, body, .. } => {
                if !effects.is_empty() {
                    let set = effects.iter().map(|e| format!("\"{e}\"")).collect::<Vec<_>>().join(", ");
                    out.push_str(&format!("@rt.effectful(effects={{{set}}})\n"));
                }
                let ps = params.iter().map(|p| p.name.clone()).collect::<Vec<_>>().join(", ");
                out.push_str(&format!("def {name}({ps}):\n"));
                out.push_str(&emit_body(body, &aliases));
                if name == "main" {
                    has_main = true;
                }
            }
            Item::Tool { name, params, .. } => {
                let ps = params.iter().map(|p| p.name.clone()).collect::<Vec<_>>().join(", ");
                out.push_str(&format!("def {name}({ps}):\n    return rt.tool_stub(\"{name}\")\n"));
            }
            Item::Test { name, .. } => {
                out.push_str(&format!("# test \"{name}\" — the `nudge test` runner lands day 9–10"));
            }
        }
    }
    if has_main {
        out.push_str("\n\nif __name__ == \"__main__\":\n    _result = main()\n    if _result is not None:\n        print(_result)\n");
    }
    while out.ends_with("\n\n\n") {
        out.pop();
    }
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

fn emit_body(body: &[Stmt], aliases: &HashSet<String>) -> String {
    if body.is_empty() {
        return "    pass\n".into();
    }
    let mut out = String::new();
    let last = body.len() - 1;
    for (i, st) in body.iter().enumerate() {
        let line = match st {
            Stmt::Let { name, value, .. } => format!("{name} = {}", py(value, aliases)),
            Stmt::Assert(e) => format!("assert {}", py(e, aliases)),
            // MVP return rule: the fn's final expression is its return value.
            Stmt::ExprStmt(e) if i == last => format!("return {}", py(e, aliases)),
            Stmt::ExprStmt(e) => py(e, aliases),
        };
        out.push_str("    ");
        out.push_str(&line);
        out.push('\n');
    }
    out
}

fn is_builtin_type(n: &str) -> bool {
    matches!(n, "string" | "int" | "float" | "bool" | "none" | "()")
}

/// TypeExpr → JSON-Schema Python literal (design v1.3 §14).
fn schema_py(t: &TypeExpr, aliases: &HashSet<String>) -> String {
    match t {
        TypeExpr::Named(n) => match n.as_str() {
            "string" => "{\"type\": \"string\"}".into(),
            "int" => "{\"type\": \"integer\"}".into(),
            "float" => "{\"type\": \"number\"}".into(),
            "bool" => "{\"type\": \"boolean\"}".into(),
            "none" | "()" => "{\"type\": \"null\"}".into(),
            _ if aliases.contains(n) => n.clone(),
            _ => "{}".into(), // checker reports the unknown name (E0101)
        },
        TypeExpr::List(inner) => format!("{{\"type\": \"array\", \"items\": {}}}", schema_py(inner, aliases)),
        TypeExpr::Record(fs) => {
            let props: Vec<String> =
                fs.iter().map(|(k, ft)| format!("\"{k}\": {}", schema_py(ft, aliases))).collect();
            let req: Vec<String> = fs.iter().map(|(k, _)| format!("\"{k}\"")).collect();
            format!(
                "{{\"type\": \"object\", \"properties\": {{{}}}, \"required\": [{}]}}",
                props.join(", "),
                req.join(", ")
            )
        }
        TypeExpr::Refine(base, name, args) => {
            let extras: Vec<String> = match (name.as_str(), args.len()) {
                ("range", 2) => vec![
                    format!("\"minimum\": {}", py(&args[0], aliases)),
                    format!("\"maximum\": {}", py(&args[1], aliases)),
                ],
                ("format", 1) => {
                    let f = match &args[0] {
                        Expr::Ident(s) | Expr::Str(s) => s.as_str(),
                        _ => "url",
                    };
                    vec![format!("\"format\": \"{}\"", if f == "url" { "uri" } else { f })]
                }
                _ => vec![],
            };
            match base.as_ref() {
                TypeExpr::Named(n) if is_builtin_type(n) => {
                    let base_pair = match n.as_str() {
                        "string" => "\"type\": \"string\"",
                        "int" => "\"type\": \"integer\"",
                        "float" => "\"type\": \"number\"",
                        "bool" => "\"type\": \"boolean\"",
                        _ => "\"type\": \"string\"",
                    };
                    let all = std::iter::once(base_pair.to_string())
                        .chain(extras)
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("{{{all}}}")
                }
                _ => {
                    let b = schema_py(base, aliases);
                    if extras.is_empty() {
                        b
                    } else {
                        format!("rt.extend({b}, {{{}}})", extras.join(", "))
                    }
                }
            }
        }
    }
}

/// A `schema:` option value (Ident / [Ident]) → schema literal.
fn expr_schema_py(e: &Expr, aliases: &HashSet<String>) -> String {
    match e {
        Expr::Ident(n) => schema_py(&TypeExpr::Named(n.clone()), aliases),
        Expr::ListLit(xs) if xs.len() == 1 => match &xs[0] {
            Expr::Ident(n) => {
                schema_py(&TypeExpr::List(Box::new(TypeExpr::Named(n.clone()))), aliases)
            }
            _ => "{}".into(),
        },
        _ => "{}".into(),
    }
}

fn py(e: &Expr, aliases: &HashSet<String>) -> String {
    match e {
        Expr::Int(v) => v.to_string(),
        Expr::Float(v) => v.to_string(),
        Expr::Str(s) => py_str(s),
        Expr::Money(v) => format!("rt.USD(\"{v}\")"),
        Expr::Bool(b) => if *b { "True".into() } else { "False".into() },
        Expr::None => "None".into(),
        Expr::Ident(n) => n.clone(),
        Expr::ListLit(xs) => {
            format!("[{}]", xs.iter().map(|x| py(x, aliases)).collect::<Vec<_>>().join(", "))
        }
        Expr::Prompt { body, interpolations } => prompt_py(body, interpolations),
        Expr::LlmCall { prompt, options, repair } => llm_py(prompt, options, *repair, aliases),
        Expr::Call { func, args, kwargs } => {
            let mut parts: Vec<String> = args.iter().map(|a| py(a, aliases)).collect();
            parts.extend(kwargs.iter().map(|(k, v)| format!("{k}={}", py(v, aliases))));
            format!("{}({})", py(func, aliases), parts.join(", "))
        }
        Expr::Field { obj, name } => format!("{}.{name}", py(obj, aliases)),
        // always parenthesized: precedence is decided by the Nudge parser,
        // never re-decided by Python
        Expr::Binary { op, l, r } => {
            format!("({} {} {})", py(l, aliases), op_str(op), py(r, aliases))
        }
        Expr::Unary { op, x } => match op {
            BinOp::Sub => format!("(-{})", py(x, aliases)),
            _ => format!("(not {})", py(x, aliases)),
        },
        Expr::ParMap { coll, kwargs, params, body } => {
            let mut s = format!(
                "rt.par_map({}, lambda {}: {}",
                py(coll, aliases),
                params.join(", "),
                py(body, aliases)
            );
            for (k, v) in kwargs {
                s.push_str(&format!(", {k}={}", py(v, aliases)));
            }
            s.push(')');
            s
        }
        Expr::ParAll(xs) => {
            format!("rt.par_all([{}])", xs.iter().map(|x| py(x, aliases)).collect::<Vec<_>>().join(", "))
        }
        Expr::ParRace(xs) => {
            format!("rt.par_race([{}])", xs.iter().map(|x| py(x, aliases)).collect::<Vec<_>>().join(", "))
        }
    }
}

fn prompt_py(body: &str, interps: &[String]) -> String {
    if interps.is_empty() {
        py_str(body)
    } else {
        // keys are the literal `{...}` contents; values are Python expressions
        // valid in the enclosing scope (identifiers / dotted paths at MVP)
        let mapping = interps.iter().map(|k| format!("\"{k}\": {k}")).collect::<Vec<_>>().join(", ");
        format!("rt.render({}, {{{mapping}}})", py_str(body))
    }
}

fn llm_py(prompt: &Expr, options: &[(String, Expr)], repair: bool, aliases: &HashSet<String>) -> String {
    // NOTE: continuation lines are indented 8 spaces, assuming the call sits
    // directly under a single-depth body line (`return ...` / `x = ...`).
    let mut parts = vec![format!("prompt={}", py(prompt, aliases))];
    for (k, v) in options {
        match k.as_str() {
            "schema" => parts.push(format!("schema=rt.schema({})", expr_schema_py(v, aliases))),
            "model" => parts.push(format!("model={}", py(v, aliases))),
            "budget" => parts.push(format!("budget={}", py(v, aliases))),
            "retry" => parts.push(format!("retry={}", py(v, aliases))),
            "cache" => parts.push(match v {
                Expr::Ident(n) => format!("cache={}", py_str(n)),
                other => format!("cache={}", py(other, aliases)),
            }),
            "tags" => parts.push(format!("tags={}", py(v, aliases))),
            other => parts.push(format!("# warning: unsupported option {other}={} (ignored)", py(v, aliases))),
        }
    }
    if repair {
        parts.push("repair=True".into());
    }
    format!("rt.llm_call(\n        {},\n    )", parts.join(",\n        "))
}

fn op_str(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+", BinOp::Sub => "-", BinOp::Mul => "*", BinOp::Div => "/", BinOp::Mod => "%",
        BinOp::Eq => "==", BinOp::NotEq => "!=", BinOp::Lt => "<", BinOp::LtEq => "<=",
        BinOp::Gt => ">", BinOp::GtEq => ">=", BinOp::And => "and", BinOp::Or => "or",
        BinOp::Not => "not",
    }
}

/// Python string literal: escape the bare minimum, pass UTF-8 through verbatim.
fn py_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

// ── tests ────────────────────────────────────────────────────────────
#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::lex;
    use crate::parser::parse;

    fn gen(src: &str) -> String {
        emit(&parse(lex(src).unwrap()).unwrap())
    }

    #[test]
    fn hello_llm_golden() {
        let src = include_str!("../../../examples/hello_llm.ndg");
        let expected = "\"\"\"Generated by nudgec 0.1.0 — do not edit.\"\"\"\nimport nudge_runtime as rt\n\n\n@rt.effectful(effects={\"LLM\"})\ndef main():\n    return rt.llm_call(\n        prompt=\"Say hello to the Nudge language in one short sentence.\",\n        model=\"anthropic:sonnet-4.6\",\n        budget=rt.USD(\"0.01\"),\n    )\n\n\nif __name__ == \"__main__\":\n    _result = main()\n    if _result is not None:\n        print(_result)\n";
        assert_eq!(gen(src), expected);
    }

    #[test]
    fn llm_options_and_interpolation() {
        let src = "fn f(q: string) -> string uses LLM {\n    llm\"\"\"hi {q}\"\"\"\n    with { model: \"m\", retry: 2 with repair, cache: content_addressed, tags: [\"a\", \"b\"] }\n}";
        let out = gen(src);
        assert!(out.contains("prompt=rt.render(\"hi {q}\", {\"q\": q}),"), "got:\n{out}");
        assert!(out.contains("retry=2,"), "got:\n{out}");
        assert!(out.contains("repair=True,"), "got:\n{out}");
        assert!(out.contains("cache=\"content_addressed\","), "got:\n{out}");
        assert!(out.contains("tags=[\"a\", \"b\"],"), "got:\n{out}");
    }

    #[test]
    fn type_alias_lowers_to_schema_literal() {
        let src = "type Url = string @format(url)\ntype Finding = { claim: string, confidence: float @range(0, 1) }";
        let out = gen(src);
        assert!(out.contains("Url = rt.schema({\"type\": \"string\", \"format\": \"uri\"})"), "got:\n{out}");
        assert!(
            out.contains("Finding = rt.schema({\"type\": \"object\", \"properties\": {\"claim\": {\"type\": \"string\"}, \"confidence\": {\"type\": \"number\", \"minimum\": 0, \"maximum\": 1}}, \"required\": [\"claim\", \"confidence\"]})"),
            "got:\n{out}"
        );
    }

    #[test]
    fn schema_option_lowers_to_rt_schema() {
        let src = "type Finding = { claim: string }\nfn f() -> [Finding] uses LLM { llm\"\"\"x\"\"\" with { schema: [Finding] } }";
        let out = gen(src);
        assert!(out.contains("schema=rt.schema({\"type\": \"array\", \"items\": Finding})"), "got:\n{out}");
    }

    #[test]
    fn tool_lowers_to_stub_fn() {
        let src = "tool web_search(q: string) -> [R] { impl: mcp(\"s\").web(q) side_effects: none }";
        let out = gen(src);
        assert!(out.contains("def web_search(q):\n    return rt.tool_stub(\"web_search\")"), "got:\n{out}");
    }

    #[test]
    fn par_map_lowers_to_runtime_call() {
        let src = "fn f(angles: [string]) -> [string] { let h = par map angles |a| -> search(a) }";
        assert!(gen(src).contains("h = rt.par_map(angles, lambda a: search(a))"));
        let src = "fn f(angles: [string], hits: [string]) -> [string] { let f2 = par map(angles zip hits, concurrency = 3) |(a, h)| -> analyze(a, h) }";
        assert!(gen(src).contains("rt.par_map(zip(angles, hits), lambda a, h: analyze(a, h), concurrency=3)"));
    }

    // ── end-to-end (skipped without python3 / runtime checkout) ──────

    struct E2e {
        dir: std::path::PathBuf,
        runtime: std::path::PathBuf,
    }

    fn e2e(name: &str) -> Option<E2e> {
        use std::process::Command;
        if Command::new("python3").arg("--version").output().is_err() {
            return None;
        }
        let runtime = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../runtime");
        if !runtime.exists() {
            return None;
        }
        // unique dir per test: `cargo test` runs them in parallel threads
        let dir = std::env::temp_dir().join(format!("nudge_e2e_{}_{}", std::process::id(), name));
        std::fs::create_dir_all(&dir).unwrap();
        Some(E2e { dir, runtime })
    }

    fn run_py(e: &E2e, file: &std::path::Path, extra: &[(&str, &str)]) -> std::process::Output {
        use std::process::Command;
        let mut cmd = Command::new("python3");
        cmd.arg(file)
            .env("NUDGE_PROVIDER", "fake")
            .env("NUDGE_TRACE", e.dir.join("trace.jsonl"))
            .env("PYTHONPATH", &e.runtime);
        for (k, v) in extra {
            cmd.env(k, v);
        }
        cmd.output().unwrap()
    }

    #[test]
    fn hello_llm_runs_under_fake_provider() {
        let Some(e) = e2e("hello") else { return };
        let py = gen(include_str!("../../../examples/hello_llm.ndg"));
        let out_py = e.dir.join("hello_llm.py");
        std::fs::write(&out_py, py).unwrap();
        let output = run_py(&e, &out_py, &[]);
        assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(stdout.contains("[fake:anthropic:sonnet-4.6]"), "stdout: {stdout}");
        let log = std::fs::read_to_string(e.dir.join("trace.jsonl")).unwrap();
        assert!(log.contains("\"kind\": \"llm.call\""), "trace: {log}");
    }

    #[test]
    fn research_agent_runs_end_to_end() {
        let Some(e) = e2e("agent") else { return };
        let py = gen(include_str!("../../../examples/research_agent.ndg"));
        let out_py = e.dir.join("research_agent.py");
        std::fs::write(&out_py, py).unwrap();
        let driver = e.dir.join("drive_agent.py");
        std::fs::write(
            &driver,
            format!(
                "import sys\nsys.path.insert(0, {:?})\nimport research_agent as r\nresult = r.run(\"urban heat islands\")\nprint(\"OK\", sorted(result.keys()))\n",
                e.dir.to_string_lossy()
            ),
        )
        .unwrap();
        let output = run_py(&e, &driver, &[]);
        assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(stdout.contains("OK") && stdout.contains("findings"), "stdout: {stdout}");
        let log = std::fs::read_to_string(e.dir.join("trace.jsonl")).unwrap();
        let calls = log.lines().filter(|l| l.contains("\"llm.call\"")).count();
        assert_eq!(calls, 3, "expected 3 llm.call records, trace: {log}");
    }

    #[test]
    fn repair_round_recovers_from_schema_violation() {
        let Some(e) = e2e("repair") else { return };
        let src = "type T = { title: string }\nfn main() -> T uses LLM {\n    llm\"\"\"give me a title\"\"\" with { schema: T, model: \"m\", retry: 2 with repair }\n}";
        let out_py = e.dir.join("repair_demo.py");
        std::fs::write(&out_py, gen(src)).unwrap();
        let output = run_py(&e, &out_py, &[("NUDGE_FAKE_FAIL_FIRST", "1")]);
        assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
        assert!(String::from_utf8_lossy(&output.stdout).contains("title"), "stdout: {output:?}");
        let log = std::fs::read_to_string(e.dir.join("trace.jsonl")).unwrap();
        assert!(log.contains("schema_violation"), "trace: {log}");
        assert!(log.contains("\"repair_round\": 1"), "trace: {log}");
    }

    #[test]
    fn exhausted_repairs_raise_schema_failure() {
        let Some(e) = e2e("fail") else { return };
        let src = "type T = { title: string }\nfn main() -> T uses LLM {\n    llm\"\"\"give me a title\"\"\" with { schema: T, model: \"m\", retry: 2 with repair }\n}";
        let out_py = e.dir.join("fail_demo.py");
        std::fs::write(&out_py, gen(src)).unwrap();
        let output = run_py(&e, &out_py, &[("NUDGE_FAKE_FAIL_FIRST", "99")]);
        assert!(!output.status.success(), "expected failure, stdout: {}", String::from_utf8_lossy(&output.stdout));
        assert!(String::from_utf8_lossy(&output.stderr).contains("SchemaFailure"), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    }
}
