//! Nudge TypeScript codegen (design §14, v0.3c) — second backend.
//!
//! Emits a single `.ts` file importing `./nudge_runtime.ts`. MVP subset:
//! type aliases, tools, fns (let/return/assert), llm calls, merge, and the
//! expression forms; annotations are limited to simple TS names so tests
//! can erase them with a regex (see `strip_ts` in the tests). Deferred to
//! the full backend: `agent` blocks, `stream let` streaming, par
//! scheduling, and replay-driver tests — emitted as warning comments.

use crate::ast::*;
use std::collections::{HashMap, HashSet};

pub fn emit_ts(items: &[Item]) -> String {
    let aliases: HashSet<String> = items
        .iter()
        .filter_map(|i| match i {
            Item::TypeAlias { name, .. } => Some(name.clone()),
            _ => None,
        })
        .collect();

    let mut out = String::new();
    out.push_str("// Generated by nudgec 0.1.0 — do not edit.\nimport * as rt from \"./nudge_runtime.ts\";\n");
    let mut has_main = false;
    // callee parameter order — JS has no named arguments, so kwargs are
    // reordered into positional slots at the call site
    let sigs: HashMap<String, Vec<String>> = items
        .iter()
        .flat_map(|i| match i {
            Item::Fn { name, params, .. } | Item::Tool { name, params, .. } => {
                vec![(
                    name.clone(),
                    params.iter().map(|p| p.name.clone()).collect(),
                )]
            }
            // agent fns live in the same namespace (the checker enforces
            // uniqueness, E0102)
            Item::Agent { fns, .. } => fns
                .iter()
                .filter_map(|f| match f {
                    Item::Fn { name, params, .. } => Some((
                        name.clone(),
                        params.iter().map(|p| p.name.clone()).collect(),
                    )),
                    _ => None,
                })
                .collect(),
            _ => vec![],
        })
        .collect();
    // test slugs can collide ("a b" vs "a_b") — suffix duplicates
    let mut test_slugs: HashMap<String, usize> = HashMap::new();
    for item in items {
        out.push_str("\n\n");
        match item {
            Item::TypeAlias { name, ty } => {
                out.push_str(&format!(
                    "const {name} = rt.schema({});",
                    schema_ts(ty, &aliases, &sigs)
                ));
            }
            Item::Fn {
                name,
                params,
                ret,
                body,
                ..
            } => {
                let ps = params
                    .iter()
                    .map(|p| format!("{}: {}", p.name, ty_ts(&p.ty, &aliases)))
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!(
                    "function {name}({ps}): {} {{\n",
                    ty_ts(ret, &aliases)
                ));
                out.push_str(&emit_body(body, &aliases, &sigs, None));
                out.push('}');
                if name == "main" {
                    has_main = true;
                }
            }
            Item::Tool {
                name,
                params,
                fields,
                ..
            } => {
                let ps = params
                    .iter()
                    .map(|p| format!("{}: {}", p.name, ty_ts(&p.ty, &aliases)))
                    .collect::<Vec<_>>()
                    .join(", ");
                let arg_list = params
                    .iter()
                    .map(|p| p.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                let server = crate::codegen::impl_server(fields)
                    .map(|s| format!(", {{ server: {:?} }}", s))
                    .unwrap_or_default();
                out.push_str(&format!(
                    "function {name}({ps}): any {{\n  return rt.toolStub(\"{name}\", [{arg_list}]{server});\n}}"
                ));
            }
            Item::Test { name, body } => {
                out.push_str(&format!(
                    "function nudge_test_{}(): void {{\n",
                    crate::codegen::unique_slug(&slug_ts(name), &mut test_slugs)
                ));
                out.push_str(&emit_body(body, &aliases, &sigs, None));
                out.push('}');
            }
            Item::Agent { name, state, fns } => {
                // agent state lowering (v1.6): mirrors the python backend —
                // a runtime Proxy checkpoints every state write
                let defaults = state
                    .iter()
                    .map(|(f, _, d)| format!("\"{f}\": {}", ts(d, &aliases, &sigs)))
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!(
                    "const _state_{name} = rt.agentState(\"{name}\", {{{defaults}}});"
                ));
                // list-typed state fields drive the += → .concat lowering
                let list_fields: Vec<String> = state
                    .iter()
                    .filter(|(_, ty, _)| matches!(ty, TypeExpr::List(_)))
                    .map(|(f, _, _)| f.clone())
                    .collect();
                for f in fns {
                    if let Item::Fn {
                        name: fn_name,
                        params,
                        body,
                        effects,
                        ..
                    } = f
                    {
                        let ps = params
                            .iter()
                            .map(|p| format!("{}: {}", p.name, ty_ts(&p.ty, &aliases)))
                            .collect::<Vec<_>>()
                            .join(", ");
                        let fx = if effects.is_empty() {
                            String::new()
                        } else {
                            format!("  // effects: {}", effects.join(", "))
                        };
                        out.push_str(&format!("\n\nfunction {fn_name}({ps}) {{{fx}\n"));
                        let bound = crate::codegen::bind_state(body, name);
                        out.push_str(&emit_body(
                            &bound,
                            &aliases,
                            &sigs,
                            Some((name.as_str(), list_fields.as_slice())),
                        ));
                        out.push('}');
                        if fn_name == "main" {
                            has_main = true;
                        }
                    }
                }
            }
        }
    }
    if has_main {
        out.push_str("\n\nconst _result = main();\nif (_result !== undefined && _result !== null) console.log(_result);\n");
    }
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

fn emit_body(
    body: &[Stmt],
    aliases: &HashSet<String>,
    sigs: &HashMap<String, Vec<String>>,
    // agent name + its LIST-typed state fields: JS `array += [x]` coerces
    // to a string — list state writes must emit .concat (python parity)
    agent: Option<(&str, &[String])>,
) -> String {
    if body.is_empty() {
        return String::new();
    }
    let mut out = String::new();
    let last = body.len() - 1;
    for (i, st) in body.iter().enumerate() {
        let line = match st {
            Stmt::Let {
                name,
                value,
                stream,
                ..
            } => {
                if *stream {
                    format!("const {name} = {};  // warning: streaming not yet supported by the TS backend — plain call", ts(value, aliases, sigs))
                } else {
                    format!("const {name} = {};", ts(value, aliases, sigs))
                }
            }
            // a state write is a checkpoint — the runtime Proxy persists it
            Stmt::StateWrite { field, op, value } => {
                match agent {
                    Some((target, list_fields)) => {
                        let v = ts(value, aliases, sigs);
                        match op {
                            crate::ast::StateOp::Add if list_fields.iter().any(|f| f == field) => {
                                // Nudge list += is concat; JS += on arrays stringifies
                                format!("_state_{target}.{field} = (_state_{target}.{field}).concat({v});")
                            }
                            crate::ast::StateOp::Set => format!("_state_{target}.{field} = {v};"),
                            crate::ast::StateOp::Add => format!("_state_{target}.{field} += {v};"),
                            crate::ast::StateOp::Sub => format!("_state_{target}.{field} -= {v};"),
                        }
                    }
                    // emit without a prior check pass stays panic-free — the
                    // checker reports E0701; mark the spot instead of panicking
                    None => format!(
                        "// error: state write 'state.{field}' outside an agent block (E0701)"
                    ),
                }
            }
            Stmt::Assert(e) => format!(
                "if (!({})) throw new Error(\"assertion failed\");",
                ts(e, aliases, sigs)
            ),
            Stmt::ExprStmt(e) if i == last => format!("return {};", ts(e, aliases, sigs)),
            Stmt::ExprStmt(e) => format!("{};", ts(e, aliases, sigs)),
        };
        out.push_str("  ");
        out.push_str(&line);
        out.push('\n');
    }
    out
}

/// Nudge type → simple TS annotation (erasable: identifiers only).
fn ty_ts(t: &TypeExpr, aliases: &HashSet<String>) -> String {
    match t {
        TypeExpr::Named(n) => match n.as_str() {
            "string" => "string".into(),
            "int" | "float" => "number".into(),
            "bool" => "boolean".into(),
            "none" | "()" => "null".into(),
            _ if aliases.contains(n) => "any".into(),
            _ => "any".into(),
        },
        TypeExpr::List(_) => "any[]".into(),
        TypeExpr::Record(_) => "Record<string, any>".into(),
        TypeExpr::Refine(base, ..) => ty_ts(base, aliases),
    }
}

fn schema_ts(
    t: &TypeExpr,
    aliases: &HashSet<String>,
    sigs: &HashMap<String, Vec<String>>,
) -> String {
    match t {
        TypeExpr::Named(n) => match n.as_str() {
            "string" => "{\"type\": \"string\"}".into(),
            "int" => "{\"type\": \"integer\"}".into(),
            "float" => "{\"type\": \"number\"}".into(),
            "bool" => "{\"type\": \"boolean\"}".into(),
            "none" | "()" => "{\"type\": \"null\"}".into(),
            _ if aliases.contains(n) => n.clone(),
            _ => "{}".into(),
        },
        TypeExpr::List(inner) => format!(
            "{{\"type\": \"array\", \"items\": {}}}",
            schema_ts(inner, aliases, sigs)
        ),
        TypeExpr::Record(fs) => {
            let props: Vec<String> = fs
                .iter()
                .map(|(k, ft)| format!("\"{k}\": {}", schema_ts(ft, aliases, sigs)))
                .collect();
            let req: Vec<String> = fs.iter().map(|(k, _)| format!("\"{k}\"")).collect();
            format!(
                "{{\"type\": \"object\", \"properties\": {{{}}}, \"required\": [{}]}}",
                props.join(", "),
                req.join(", ")
            )
        }
        TypeExpr::Refine(base, name, args) => {
            let extras: Vec<String> = match (name.as_str(), args.len()) {
                ("range", 2) => vec![
                    format!("\"minimum\": {}", ts(&args[0], aliases, sigs)),
                    format!("\"maximum\": {}", ts(&args[1], aliases, sigs)),
                ],
                ("format", 1) => {
                    let f = match &args[0] {
                        Expr::Ident(s) | Expr::Str(s) => s.as_str(),
                        _ => "url",
                    };
                    vec![format!(
                        "\"format\": \"{}\"",
                        if f == "url" { "uri" } else { f }
                    )]
                }
                _ => vec![],
            };
            match base.as_ref() {
                TypeExpr::Named(n)
                    if matches!(
                        n.as_str(),
                        "string" | "int" | "float" | "bool" | "none" | "()"
                    ) =>
                {
                    let base_pair = match n.as_str() {
                        "string" => "\"type\": \"string\"",
                        "int" => "\"type\": \"integer\"",
                        "float" => "\"type\": \"number\"",
                        "bool" => "\"type\": \"boolean\"",
                        _ => "\"type\": \"string\"",
                    };
                    let all = std::iter::once(base_pair.to_string())
                        .chain(extras)
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("{{{all}}}")
                }
                _ => {
                    let b = schema_ts(base, aliases, sigs);
                    if extras.is_empty() {
                        b
                    } else {
                        format!("rt.extend({b}, {{{}}})", extras.join(", "))
                    }
                }
            }
        }
    }
}

fn expr_schema_ts(
    e: &Expr,
    aliases: &HashSet<String>,
    sigs: &HashMap<String, Vec<String>>,
) -> String {
    match e {
        Expr::Ident(n) => schema_ts(&TypeExpr::Named(n.clone()), aliases, sigs),
        Expr::ListLit(xs) if xs.len() == 1 => match &xs[0] {
            Expr::Ident(n) => schema_ts(
                &TypeExpr::List(Box::new(TypeExpr::Named(n.clone()))),
                aliases,
                sigs,
            ),
            _ => "{}".into(),
        },
        _ => "{}".into(),
    }
}

fn ts(e: &Expr, aliases: &HashSet<String>, sigs: &HashMap<String, Vec<String>>) -> String {
    match e {
        Expr::Int(v) => v.to_string(),
        Expr::Float(v) => crate::codegen::fmt_f64(*v),
        Expr::Str(s) => js_str(s),
        Expr::Money(v, _) => format!("rt.USD(\"{v}\")"),
        Expr::Bool(b) => {
            if *b {
                "true".into()
            } else {
                "false".into()
            }
        }
        Expr::None => "null".into(),
        Expr::Ident(n) => n.clone(),
        Expr::ListLit(xs) => {
            format!(
                "[{}]",
                xs.iter()
                    .map(|x| ts(x, aliases, sigs))
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        }
        Expr::Prompt {
            body,
            interpolations,
        } => {
            if interpolations.is_empty() {
                js_str(body)
            } else {
                let mapping = interpolations
                    .iter()
                    .map(|k| format!("\"{k}\": {k}"))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("rt.render({}, {{{mapping}}})", js_str(body))
            }
        }
        Expr::LlmCall {
            prompt,
            options,
            repair,
        } => llm_ts(prompt, options, *repair, aliases, sigs),
        Expr::Call { func, args, kwargs } => {
            let mut parts: Vec<String> = args.iter().map(|a| ts(a, aliases, sigs)).collect();
            // JS has no named arguments — emitting `f(k: v)` was a syntax
            // error. For a known callee, kwargs drop into their declared
            // parameter slots (the checker has already matched the names);
            // for an unknown one, they go as a trailing options object.
            match func.as_ref() {
                Expr::Ident(n) if sigs.contains_key(n) => {
                    let order = &sigs[n];
                    for pname in order.iter().skip(args.len()) {
                        match kwargs.iter().find(|(k, _)| k == pname) {
                            Some((_, v)) => parts.push(ts(v, aliases, sigs)),
                            None => parts.push("undefined".into()),
                        }
                    }
                }
                _ => {
                    parts.extend(
                        kwargs
                            .iter()
                            .map(|(k, v)| format!("{{ {k}: {} }}", ts(v, aliases, sigs))),
                    );
                }
            }
            match func.as_ref() {
                Expr::Ident(n) if n == "len" => {
                    // the checker enforces arity (E0201); stay panic-free if
                    // emit is ever driven without a prior check pass
                    match args.first() {
                        Some(a) => format!("({}.length)", ts(a, aliases, sigs)),
                        None => "(undefined).length".into(),
                    }
                }
                Expr::Ident(n) if matches!(n.as_str(), "replay" | "python" | "mcp" | "zip") => {
                    format!("rt.{n}({})", parts.join(", "))
                }
                other => format!("{}({})", ts(other, aliases, sigs), parts.join(", ")),
            }
        }
        Expr::Field { obj, name } => format!("{}.{name}", ts(obj, aliases, sigs)),
        Expr::Binary { op, l, r } => {
            let o = match op {
                BinOp::And => "&&",
                BinOp::Or => "||",
                other => crate::codegen::op_str(other),
            };
            format!("({} {} {})", ts(l, aliases, sigs), o, ts(r, aliases, sigs))
        }
        Expr::Unary { op, x } => match op {
            BinOp::Sub => format!("(-{})", ts(x, aliases, sigs)),
            _ => format!("(!{})", ts(x, aliases, sigs)),
        },
        Expr::ParMap {
            coll,
            kwargs,
            params,
            body,
        } => {
            // MVP: sequential map (no worker pool in the TS runtime yet).
            // JS `Array.map` passes (element, index) — a multi-param lambda
            // must take ONE element and destructure the zipped pair
            // ({first, second}), or the second param silently becomes the index.
            let mut s = if params.len() == 2 {
                format!(
                    "rt.parMap({}, (__e) => {{ const {} = __e.first; const {} = __e.second; return {}; }})",
                    ts(coll, aliases, sigs),
                    params[0],
                    params[1],
                    ts(body, aliases, sigs)
                )
            } else {
                format!(
                    "rt.parMap({}, ({}) => {})",
                    ts(coll, aliases, sigs),
                    params.join(", "),
                    ts(body, aliases, sigs)
                )
            };
            if !kwargs.is_empty() {
                s.push_str(
                    "  // warning: par map kwargs ignored by the TS backend (sequential map)",
                );
            }
            s
        }
        // thunks, not values: the runtime wraps each lane's evaluation in
        // its NTF v1.1 branch label — and a plain array return fixes the
        // old un-awaited Promise.all leaking a Promise into `let` bindings
        Expr::ParAll(xs) => {
            format!(
                "rt.parAll([{}])",
                xs.iter()
                    .map(|x| format!("() => {}", ts(x, aliases, sigs)))
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        }
        Expr::ParRace(xs) => {
            format!(
                "rt.parRace([{}])",
                xs.iter()
                    .map(|x| format!("() => {}", ts(x, aliases, sigs)))
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        }
        Expr::Merge { l, r } => format!(
            "rt.merge({}, {})",
            ts(l, aliases, sigs),
            ts(r, aliases, sigs)
        ),
        Expr::Route { arms } => {
            let parts = arms
                .iter()
                .map(|(label, model, cond)| match cond {
                    Some(c) => {
                        format!("[{:?}, {:?}, () => {}]", label, model, ts(c, aliases, sigs))
                    }
                    None => format!("[{:?}, {:?}, null]", label, model),
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!("rt.route({parts})")
        }
    }
}

fn llm_ts(
    prompt: &Expr,
    options: &[(String, Expr)],
    repair: bool,
    aliases: &HashSet<String>,
    sigs: &HashMap<String, Vec<String>>,
) -> String {
    let mut parts = vec![format!("prompt: {}", ts(prompt, aliases, sigs))];
    for (k, v) in options {
        match k.as_str() {
            "schema" => parts.push(format!(
                "schema: rt.schema({})",
                expr_schema_ts(v, aliases, sigs)
            )),
            "model" => parts.push(format!("model: {}", ts(v, aliases, sigs))),
            "budget" => parts.push(format!("budget: {}", ts(v, aliases, sigs))),
            "retry" => parts.push(format!("retry: {}", ts(v, aliases, sigs))),
            "cache" => parts.push(match v {
                Expr::Ident(n) => format!("cache: {}", js_str(n)),
                other => format!("cache: {}", ts(other, aliases, sigs)),
            }),
            "tags" => parts.push(format!("tags: {}", ts(v, aliases, sigs))),
            other => parts.push(format!(
                "/* warning: unsupported option {other} (ignored) */"
            )),
        }
    }
    if repair {
        parts.push("repair: true".into());
    }
    format!("rt.llmCall({{{}}})", parts.join(", "))
}

/// `test "run stays within budget"` → `run_stays_within_budget`.
fn slug_ts(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut last_us = true;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
            last_us = false;
        } else if !last_us {
            out.push('_');
            last_us = true;
        }
    }
    while out.ends_with('_') {
        out.pop();
    }
    if out.is_empty() {
        "unnamed".into()
    } else {
        out
    }
}

/// JS string literal: escape the bare minimum, pass UTF-8 through verbatim.
fn js_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

// ── tests ────────────────────────────────────────────────────────────
#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::lex;
    use crate::parser::parse;

    fn gen_ts(src: &str) -> String {
        emit_ts(&parse(lex(src).unwrap()).unwrap())
    }

    /// Erase the simple annotation forms the emitter produces (test-only;
    /// lets node run the output without a TS toolchain). Dependency-free:
    /// scans for `: <SimpleTy>` followed by one of `, ) { = ; <space>`.
    fn strip_ts(code: &str) -> String {
        const TYS: [&str; 8] = [
            "Record<string, any>",
            "string",
            "number",
            "boolean",
            "null",
            "any[]",
            "any",
            "void",
        ];
        let mut out = String::with_capacity(code.len());
        let mut rest = code;
        while let Some(pos) = rest.find(": ") {
            let after = &rest[pos + 2..];
            let hit = TYS.iter().find_map(|t| {
                after
                    .strip_prefix(t)
                    .filter(|a2| a2.starts_with([',', ')', '{', '=', ';', ' ']))
                    .map(|_| t)
            });
            match hit {
                Some(t) => {
                    out.push_str(&rest[..pos]);
                    rest = &after[t.len()..];
                }
                None => {
                    out.push_str(&rest[..pos + 2]);
                    rest = after;
                }
            }
        }
        out.push_str(rest);
        out
    }

    #[test]
    fn ts_hello_llm_shape() {
        let out = gen_ts(include_str!("../../../examples/hello_llm.ndg"));
        assert!(
            out.contains("import * as rt from \"./nudge_runtime.ts\";"),
            "got:\n{out}"
        );
        assert!(out.contains("function main(): string {"), "got:\n{out}");
        assert!(out.contains("return rt.llmCall({prompt: \"Say hello to the Nudge language in one short sentence.\", model: \"anthropic:sonnet-4.6\", budget: rt.USD(\"0.01\")});"), "got:\n{out}");
    }

    #[test]
    fn ts_types_tools_and_merge() {
        let src = "type F = { claim: string }\ntool search(q: string) -> [F] { impl: mcp(\"s\").web(q) side_effects: none }\nfn f(q: string) -> [F] uses LLM { let a = llm\"\"\"c {q}\"\"\" with { schema: [F], model: \"m\" }\n    a | merge a }";
        let out = gen_ts(src);
        assert!(out.contains("const F = rt.schema({\"type\": \"object\", \"properties\": {\"claim\": {\"type\": \"string\"}}, \"required\": [\"claim\"]});"), "got:\n{out}");
        assert!(
            out.contains("return rt.toolStub(\"search\", [q], { server: \"s\" });"),
            "got:\n{out}"
        );
        assert!(
            out.contains("schema: rt.schema({\"type\": \"array\", \"items\": F})"),
            "got:\n{out}"
        );
        assert!(out.contains("return rt.merge(a, a);"), "got:\n{out}");
        assert!(
            out.contains("function f(q: string): any[] {"),
            "got:\n{out}"
        );
        assert_eq!(
            strip_ts("function f(q: string): any[] {"),
            "function f(q) {"
        );
    }

    #[test]
    fn ts_agent_and_stream_warn() {
        // v1.6: agents lower to rt.agentState + a checkpointing Proxy
        let src =
            "agent A {\n    state {\n        n: int = 0,\n    }\n    fn step() -> int {\n        state.n += 1\n        state.n\n    }\n}";
        let out = gen_ts(src);
        assert!(
            out.contains("const _state_A = rt.agentState(\"A\", {\"n\": 0});"),
            "got:\n{out}"
        );
        assert!(out.contains("_state_A.n += 1;"), "got:\n{out}");
        assert!(!out.contains("skipped"), "got:\n{out}");
        let src2 = "fn f() -> string uses LLM { stream let t: string = llm\"\"\"x\"\"\" with { model: \"m\" }\n    t }";
        let out2 = gen_ts(src2);
        assert!(
            out2.contains("warning: streaming not yet supported by the TS backend"),
            "got:\n{out2}"
        );
    }

    // ── v1.3 regression: two-param par map lambdas destructure the pair ──
    // JS `Array.map` hands the callback (element, index) — emitting
    // `.map((a, h) => …)` used to bind the INDEX to `h`. The lambda must
    // take one element and destructure the {first, second} zip pair.
    #[test]
    fn ts_par_map_two_params_destructures_the_element() {
        let src = "fn f(xs: [string], ys: [string]) -> [string] uses LLM { par map(xs zip ys) |(a, b)| -> a }";
        let out = gen_ts(src);
        assert!(
            out.contains("rt.parMap(")
                && out
                    .contains("(__e) => { const a = __e.first; const b = __e.second; return a; }"),
            "got:\n{out}"
        );
        // single-param lambdas keep the direct form
        let out = gen_ts("fn f(xs: [string]) -> [string] uses LLM { par map xs |x| -> x }");
        assert!(out.contains("rt.parMap(xs, (x) => x)"), "got:\n{out}");
        // and the emitted JS actually computes the zip semantics under node
        use std::process::Command;
        if Command::new("node").arg("--version").output().is_err() {
            return;
        }
        let js = "const xs = [1,2,3]; const ys = [10,20,30];\
            const zip = (a, b) => a.slice(0, Math.min(a.length, b.length)).map((v, i) => ({ first: v, second: b[i] }));\
            const out = zip(xs, ys).map((__e) => { const a = __e.first; const b = __e.second; return a + b; });\
            if (JSON.stringify(out) !== JSON.stringify([11,22,33])) { console.error(out); process.exit(1); }";
        let st = Command::new("node").arg("-e").arg(js).status().unwrap();
        assert!(st.success());
    }

    // ── v1.4 regression: kwargs emit as positional slots, not `f(k: v)` ──
    #[test]
    fn ts_kwargs_land_in_declared_parameter_order() {
        let src = "fn g(a: int, b: int) -> int { a + b }\nfn f() -> int { g(1, b = 2) }";
        let out = gen_ts(src);
        assert!(out.contains("g(1, 2)"), "got:\n{out}");
        assert!(!out.contains("b: 2"), "got:\n{out}");
        // out-of-order kwargs still land in the right slot
        let src = "fn g(a: int, b: int) -> int { a + b }\nfn f() -> int { g(b = 2, a = 1) }";
        let out = gen_ts(src);
        assert!(out.contains("g(1, 2)"), "got:\n{out}");
    }

    #[test]
    fn ts_route_block_lowers_to_rt_route() {
        let src = "fn pick(flag: bool) -> string uses LLM {\n    llm\"\"\"hi\"\"\" with { model: route{ cheap: \"m1\" when flag, strong: \"m2\" otherwise } }\n}";
        let out = gen_ts(src);
        assert!(
            out.contains("rt.route([\"cheap\", \"m1\", () => flag], [\"strong\", \"m2\", null])"),
            "got:\n{out}"
        );
        // annotation-stripped output stays valid JS
        assert!(
            strip_ts(&out).contains("rt.route([\"cheap\", \"m1\", () => flag]"),
            "got:\n{out}"
        );
    }

    // ── end-to-end (skipped without node / runtime checkout) ──────

    // ── v1.6 e2e: TS agent state checkpoints + resume under node ─────
    #[test]
    fn ts_agent_state_checkpoints_and_resumes_under_node() {
        use std::process::Command;
        if Command::new("node").arg("--version").output().is_err() {
            return;
        }
        let runtime = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../runtime");
        if !runtime.exists() {
            return;
        }
        let dir = std::env::temp_dir().join(format!("nudge_tsagent_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let src = "agent A {\n    state {\n        notes: [string] = [],\n        round: int = 0,\n    }\n    fn step() -> int {\n        state.notes += [\"a\"]\n        state.round += 1\n        state.notes += [\"b\"]\n        state.round += 1\n        state.round\n    }\n    fn main() -> int {\n        step()\n    }\n}";
        let emitted = strip_ts(&gen_ts(src)).replace("./nudge_runtime.ts", "./nudge_runtime.mjs");
        std::fs::write(dir.join("agent.mjs"), &emitted).unwrap();
        let rt_src = std::fs::read_to_string(runtime.join("nudge_runtime.ts")).unwrap();
        std::fs::write(dir.join("nudge_runtime.mjs"), rt_src).unwrap();

        // fresh run: checkpoint must reflect every write
        let out = Command::new("node")
            .arg(dir.join("agent.mjs"))
            .env("NUDGE_RUN_ID", "tsr1")
            .current_dir(&dir)
            .output()
            .unwrap();
        assert!(
            out.status.success(),
            "stderr: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        assert_eq!(String::from_utf8_lossy(&out.stdout).trim(), "2");
        let ckpt = std::fs::read_to_string(dir.join(".nudge/runs/tsr1/checkpoint.json")).unwrap();
        assert!(ckpt.contains("\"writes\": 4"), "checkpoint: {ckpt}");
        assert!(
            ckpt.contains("\"a\"") && ckpt.contains("\"b\""),
            "checkpoint: {ckpt}"
        );

        // faithful resume: the prefix replays from defaults, the guard
        // passes, and += does not double-apply
        let out = Command::new("node")
            .arg(dir.join("agent.mjs"))
            .env("NUDGE_RUN_ID", "tsr1")
            .env("NUDGE_RESUME", "1")
            .current_dir(&dir)
            .output()
            .unwrap();
        assert!(
            out.status.success(),
            "stderr: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        assert_eq!(String::from_utf8_lossy(&out.stdout).trim(), "2");

        // diverged resume: the program changed since the "crash" — the
        // guard must abort with ReplayMismatch
        let changed = emitted.replace("\"b\"", "\"CHANGED\"");
        std::fs::write(dir.join("agent.mjs"), changed).unwrap();
        let out = Command::new("node")
            .arg(dir.join("agent.mjs"))
            .env("NUDGE_RUN_ID", "tsr1")
            .env("NUDGE_RESUME", "1")
            .current_dir(&dir)
            .output()
            .unwrap();
        assert!(!out.status.success(), "diverged resume must fail");
        assert!(
            String::from_utf8_lossy(&out.stderr).contains("ReplayMismatch"),
            "stderr: {}",
            String::from_utf8_lossy(&out.stderr)
        );
    }

    #[test]
    fn ts_hello_runs_under_node() {
        use std::process::Command;
        if Command::new("node").arg("--version").output().is_err() {
            return;
        }
        let runtime = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../runtime");
        if !runtime.exists() {
            return;
        }
        let dir = std::env::temp_dir().join(format!("nudge_tse2e_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        // the emitted .ts is annotation-stripped so plain node can run it;
        // the runtime ships plain JS and only needs the rename
        let emitted = strip_ts(&gen_ts(include_str!("../../../examples/hello_llm.ndg")))
            .replace("./nudge_runtime.ts", "./nudge_runtime.mjs");
        std::fs::write(dir.join("hello.mjs"), emitted).unwrap();
        let rt_src = std::fs::read_to_string(runtime.join("nudge_runtime.ts")).unwrap();
        std::fs::write(dir.join("nudge_runtime.mjs"), rt_src).unwrap();
        let out = Command::new("node")
            .arg(dir.join("hello.mjs"))
            .env("NUDGE_PROVIDER", "fake")
            .env("NUDGE_TRACE", dir.join("trace.jsonl"))
            .current_dir(&dir)
            .output()
            .unwrap();
        assert!(
            out.status.success(),
            "stderr: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        let stdout = String::from_utf8_lossy(&out.stdout);
        assert!(
            stdout.contains("[fake:anthropic:sonnet-4.6]"),
            "stdout: {stdout}"
        );
        let log = std::fs::read_to_string(dir.join("trace.jsonl")).unwrap();
        assert!(
            log.contains("\"kind\":\"llm.call\"") || log.contains("\"kind\": \"llm.call\""),
            "trace: {log}"
        );
    }

    // ── v1.2 regression: TS budget walls match the python runtime ──
    // per-call `budget` walls the single call; NUDGE_BUDGET walls the run
    // total (the TS runtime used to apply the per-call budget against the
    // cumulative run spend — a parity bug).

    #[test]
    fn ts_budget_walls_match_python_semantics() {
        use std::process::Command;
        if Command::new("node").arg("--version").output().is_err() {
            return;
        }
        let runtime = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../runtime");
        if !runtime.exists() {
            return;
        }
        let dir = std::env::temp_dir().join(format!("nudge_tsbudget_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let rt_src = std::fs::read_to_string(runtime.join("nudge_runtime.ts")).unwrap();
        std::fs::write(dir.join("nudge_runtime.mjs"), rt_src).unwrap();
        // 51 calls at $0.001 with a per-call budget of $0.05: python parity
        // says all pass (each call is well under its own wall)
        let src = "fn main() -> string uses LLM {\n    llm\"\"\"hi there, say something brief\"\"\" with { model: \"fake\", budget: 0.05 USD }\n}";
        let emitted = strip_ts(&gen_ts(src)).replace("./nudge_runtime.ts", "./nudge_runtime.mjs");
        std::fs::write(dir.join("main.mjs"), &emitted).unwrap();
        for _ in 0..51 {
            let out = Command::new("node")
                .arg(dir.join("main.mjs"))
                .env("NUDGE_PROVIDER", "fake")
                .env("NUDGE_TRACE", dir.join("trace.jsonl"))
                .current_dir(&dir)
                .output()
                .unwrap();
            assert!(
                out.status.success(),
                "per-call wall must not fire: {}",
                String::from_utf8_lossy(&out.stderr)
            );
        }
        // run wall: NUDGE_BUDGET=0.0005 < one $0.001 call → BudgetExceeded
        let out = Command::new("node")
            .arg(dir.join("main.mjs"))
            .env("NUDGE_PROVIDER", "fake")
            .env("NUDGE_TRACE", dir.join("trace2.jsonl"))
            .env("NUDGE_BUDGET", "0.0005")
            .current_dir(&dir)
            .output()
            .unwrap();
        assert!(!out.status.success(), "run wall must fire");
        let stderr = String::from_utf8_lossy(&out.stderr);
        assert!(stderr.contains("BudgetExceeded"), "stderr: {stderr}");
    }
}
