//! Nudge Python codegen (design §14 contract, v1.10) — day 4–6 scope.
//!
//! Lowers the AST to a single deterministic Python file importing only
//! stdlib + `nudge_runtime`:
//!   type alias  → `Name = rt.schema({...})` JSON-Schema literal (records are
//!                 plain dicts validated at runtime; dataclasses post-MVP)
//!   tool        → `def name(...): return rt.tool_stub("name", [args])` (real
//!                 MCP wiring lands post-MVP; traced as `tool.call` records)
//!   llm call    → `rt.llm_call(prompt=…, schema=rt.schema(…), model=…, …)`
//!   stream let  → `rt.llm_stream(…)` (design §4.5: incremental schema
//!                 validation, early abort on unsatisfiable prefixes)
//!   agent state → `_state_<A> = rt.AgentState("A", {defaults})`; `state.x`
//!                 reads re-root to it, writes checkpoint on every store (§7)
//!   merge       → `rt.merge(l, r)` (design §7: dict union / list dedup)
//!   test block  → `def nudge_test_<slug>():` (design §6.3; run via
//!                 `nudgec test`) with `replay` → `rt.replay`
//!
//! Determinism (design §14 rule d): identical AST ⇒ byte-identical output.

use crate::ast::*;
use std::collections::{HashMap, HashSet};

pub fn emit(items: &[Item]) -> String {
    let aliases: HashSet<String> = items
        .iter()
        .filter_map(|i| match i {
            Item::TypeAlias { name, .. } => Some(name.clone()),
            _ => None,
        })
        .collect();

    let mut out = String::new();
    out.push_str(
        "\"\"\"Generated by nudgec 0.1.0 — do not edit.\"\"\"\nimport nudge_runtime as rt\n",
    );
    let mut has_main = false;
    // test slugs can collide ("a b" vs "a_b") — suffix duplicates so no
    // test silently overwrites another in the emitted module
    let mut test_slugs: HashMap<String, usize> = HashMap::new();
    for item in items {
        out.push_str("\n\n");
        match item {
            Item::TypeAlias { name, ty } => {
                out.push_str(&format!("{name} = rt.schema({})", schema_py(ty, &aliases)));
            }
            Item::Fn {
                name,
                params,
                effects,
                body,
                ..
            } => {
                if !effects.is_empty() {
                    let set = effects
                        .iter()
                        .map(|e| format!("\"{e}\""))
                        .collect::<Vec<_>>()
                        .join(", ");
                    out.push_str(&format!("@rt.effectful(effects={{{set}}})\n"));
                }
                let ps = params
                    .iter()
                    .map(|p| p.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!("def {name}({ps}):\n"));
                out.push_str(&emit_body(body, &aliases, None));
                if name == "main" {
                    has_main = true;
                }
            }
            Item::Tool {
                name,
                params,
                fields,
                ..
            } => {
                let ps = params
                    .iter()
                    .map(|p| p.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                let arg_list = params
                    .iter()
                    .map(|p| p.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                // design §8: `impl: mcp("server").tool(...)` routes the stub
                // through that server in the runtime registry
                let server = impl_server(fields)
                    .map(|s| format!(", server={}", py_str(&s)))
                    .unwrap_or_default();
                out.push_str(&format!("def {name}({ps}):\n    return rt.tool_stub(\"{name}\", [{arg_list}]{server})\n"));
            }
            Item::Test { name, body } => {
                out.push_str(&format!(
                    "def nudge_test_{}():\n",
                    unique_slug(&slug(name), &mut test_slugs)
                ));
                out.push_str(&emit_test_body(body, &aliases));
            }
            Item::Agent { name, state, fns } => {
                // design §7 (v0.2c): state defaults lower to a checkpointed
                // AgentState object; agent fns are plain module-level defs
                let defaults = state
                    .iter()
                    .map(|(f, _, d)| format!("\"{f}\": {}", py(d, &aliases)))
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!(
                    "_state_{name} = rt.AgentState(\"{name}\", {{{defaults}}})\n"
                ));
                for f in fns {
                    if let Item::Fn {
                        name: fn_name,
                        params,
                        effects,
                        body,
                        ..
                    } = f
                    {
                        if !effects.is_empty() {
                            let set = effects
                                .iter()
                                .map(|e| format!("\"{e}\""))
                                .collect::<Vec<_>>()
                                .join(", ");
                            out.push_str(&format!("@rt.effectful(effects={{{set}}})\n"));
                        }
                        let ps = params
                            .iter()
                            .map(|p| p.name.clone())
                            .collect::<Vec<_>>()
                            .join(", ");
                        out.push_str(&format!("def {fn_name}({ps}):\n"));
                        let bound = bind_state(body, name);
                        out.push_str(&emit_body(&bound, &aliases, Some(name)));
                        if fn_name == "main" {
                            has_main = true;
                        }
                    }
                }
            }
        }
    }
    if has_main {
        out.push_str("\n\nif __name__ == \"__main__\":\n    _result = main()\n    if _result is not None:\n        print(_result)\n");
    }
    while out.ends_with("\n\n\n") {
        out.pop();
    }
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

fn emit_body(body: &[Stmt], aliases: &HashSet<String>, agent: Option<&str>) -> String {
    if body.is_empty() {
        return "    pass\n".into();
    }
    let mut out = String::new();
    let last = body.len() - 1;
    for (i, st) in body.iter().enumerate() {
        let line = match &st.kind {
            StmtKind::Let {
                name,
                value,
                stream,
                ..
            } => {
                if *stream {
                    match value {
                        // design §4.5: stream let lowers to the incremental-validating stream call
                        Expr::LlmCall {
                            prompt,
                            options,
                            repair,
                        } => {
                            format!(
                                "{name} = {}",
                                llm_py(true, prompt, options, *repair, aliases)
                            )
                        }
                        _ => format!(
                            "{name} = {}  # warning: stream ignored on non-llm binding",
                            py(value, aliases)
                        ),
                    }
                } else {
                    format!("{name} = {}", py(value, aliases))
                }
            }
            // design §7: a state write is a checkpoint — attribute writes on
            // the AgentState object persist automatically
            StmtKind::StateWrite { field, op, value } => match agent {
                Some(target) => {
                    let op = match op {
                        StateOp::Set => "=",
                        StateOp::Add => "+=",
                        StateOp::Sub => "-=",
                    };
                    format!("_state_{target}.{field} {op} {}", py(value, aliases))
                }
                // emit without a prior check pass stays panic-free — the
                // checker reports E0701; mark the spot instead of panicking
                None => format!(
                    "# error: state write 'state.{field}' outside an agent block (E0701)\n    pass"
                ),
            },
            StmtKind::Assert(e) => format!("assert {}", py(e, aliases)),
            // MVP return rule: the fn's final expression is its return value.
            StmtKind::ExprStmt(e) if i == last => format!("return {}", py(e, aliases)),
            StmtKind::ExprStmt(e) => py(e, aliases),
        };
        out.push_str("    ");
        out.push_str(&line);
        out.push('\n');
    }
    out
}

/// Test bodies (design §6.3): no implicit return — asserts do the work.
fn emit_test_body(body: &[Stmt], aliases: &HashSet<String>) -> String {
    if body.is_empty() {
        return "    pass\n".into();
    }
    let mut out = String::new();
    for st in body {
        let line = match &st.kind {
            StmtKind::Let {
                name,
                value,
                stream,
                ..
            } => {
                if *stream {
                    match value {
                        // design §4.5: stream let lowers to the incremental-validating stream call
                        Expr::LlmCall {
                            prompt,
                            options,
                            repair,
                        } => {
                            format!(
                                "{name} = {}",
                                llm_py(true, prompt, options, *repair, aliases)
                            )
                        }
                        _ => format!(
                            "{name} = {}  # warning: stream ignored on non-llm binding",
                            py(value, aliases)
                        ),
                    }
                } else {
                    format!("{name} = {}", py(value, aliases))
                }
            }
            // the checker reports E0701 — stay panic-free when emit is
            // driven without a prior check pass (fuzz harness does this)
            StmtKind::StateWrite { field, .. } => {
                format!(
                    "# error: state write 'state.{field}' outside an agent block (E0701)\n    pass"
                )
            }
            StmtKind::Assert(e) => format!("assert {}", py(e, aliases)),
            StmtKind::ExprStmt(e) => py(e, aliases),
        };
        out.push_str("    ");
        out.push_str(&line);
        out.push('\n');
    }
    out
}

/// Bind `state` reads inside an agent fn to its checkpointed state object
/// (design §7): `state.round` → `_state_<Agent>.round`. State *writes* stay
/// `StmtKind::StateWrite` — emit_body renders them with the same target.
pub fn bind_state(body: &[Stmt], agent: &str) -> Vec<Stmt> {
    body.iter()
        .map(|st| {
            let kind = match &st.kind {
                StmtKind::Let {
                    name,
                    ty,
                    value,
                    stream,
                } => StmtKind::Let {
                    name: name.clone(),
                    ty: ty.clone(),
                    value: bind_state_expr(value, agent),
                    stream: *stream,
                },
                StmtKind::StateWrite { field, op, value } => StmtKind::StateWrite {
                    field: field.clone(),
                    op: *op,
                    value: bind_state_expr(value, agent),
                },
                StmtKind::Assert(e) => StmtKind::Assert(bind_state_expr(e, agent)),
                StmtKind::ExprStmt(e) => StmtKind::ExprStmt(bind_state_expr(e, agent)),
            };
            Stmt {
                kind,
                span: st.span,
            }
        })
        .collect()
}

fn bind_state_expr(e: &Expr, agent: &str) -> Expr {
    match e {
        Expr::Ident(n) if n == "state" => Expr::Ident(format!("_state_{agent}")),
        Expr::ListLit(xs) => Expr::ListLit(xs.iter().map(|x| bind_state_expr(x, agent)).collect()),
        Expr::Prompt {
            body,
            interpolations,
        } => {
            // interpolation keys double as Python expressions in the emitted
            // render mapping, so state references must be re-rooted in BOTH
            // the template body and the key list (they must stay in sync)
            let mut body = body.clone();
            let mut interps = Vec::with_capacity(interpolations.len());
            for k in interpolations {
                if k == "state" {
                    body = body.replace("{state}", &format!("{{_state_{agent}}}"));
                    interps.push(format!("_state_{agent}"));
                } else if let Some(rest) = k.strip_prefix("state.") {
                    body = body.replace(
                        &format!("{{state.{rest}}}"),
                        &format!("{{_state_{agent}.{rest}}}"),
                    );
                    interps.push(format!("_state_{agent}.{rest}"));
                } else {
                    interps.push(k.clone());
                }
            }
            Expr::Prompt {
                body,
                interpolations: interps,
            }
        }
        Expr::LlmCall {
            prompt,
            options,
            repair,
        } => Expr::LlmCall {
            prompt: Box::new(bind_state_expr(prompt, agent)),
            options: options
                .iter()
                .map(|(k, v)| (k.clone(), bind_state_expr(v, agent)))
                .collect(),
            repair: *repair,
        },
        Expr::Call { func, args, kwargs } => Expr::Call {
            func: Box::new(bind_state_expr(func, agent)),
            args: args.iter().map(|a| bind_state_expr(a, agent)).collect(),
            kwargs: kwargs
                .iter()
                .map(|(k, v)| (k.clone(), bind_state_expr(v, agent)))
                .collect(),
        },
        Expr::Field { obj, name } => Expr::Field {
            obj: Box::new(bind_state_expr(obj, agent)),
            name: name.clone(),
        },
        Expr::Binary { op, l, r } => Expr::Binary {
            op: op.clone(),
            l: Box::new(bind_state_expr(l, agent)),
            r: Box::new(bind_state_expr(r, agent)),
        },
        Expr::Unary { op, x } => Expr::Unary {
            op: op.clone(),
            x: Box::new(bind_state_expr(x, agent)),
        },
        Expr::ParMap {
            coll,
            kwargs,
            params,
            body,
        } => Expr::ParMap {
            coll: Box::new(bind_state_expr(coll, agent)),
            kwargs: kwargs
                .iter()
                .map(|(k, v)| (k.clone(), bind_state_expr(v, agent)))
                .collect(),
            params: params.clone(),
            body: Box::new(bind_state_expr(body, agent)),
        },
        Expr::ParAll(xs) => Expr::ParAll(xs.iter().map(|x| bind_state_expr(x, agent)).collect()),
        Expr::ParRace(xs) => Expr::ParRace(xs.iter().map(|x| bind_state_expr(x, agent)).collect()),
        Expr::Merge { l, r } => Expr::Merge {
            l: Box::new(bind_state_expr(l, agent)),
            r: Box::new(bind_state_expr(r, agent)),
        },
        Expr::Route { arms } => Expr::Route {
            arms: arms
                .iter()
                .map(|(label, model, cond)| {
                    (
                        label.clone(),
                        model.clone(),
                        cond.as_ref().map(|c| bind_state_expr(c, agent)),
                    )
                })
                .collect(),
        },
        leaf => leaf.clone(),
    }
}

/// Find the MCP server in a tool's `impl: mcp("server").tool(...)` field
/// (design §8) — walks the expression for an `mcp("...")` call.
pub fn impl_server(fields: &[(String, Expr)]) -> Option<String> {
    fn find(e: &Expr) -> Option<String> {
        match e {
            Expr::Call { func, args, .. } => {
                if let Expr::Ident(n) = func.as_ref() {
                    if n == "mcp" {
                        if let Some(Expr::Str(s)) = args.first() {
                            return Some(s.clone());
                        }
                    }
                }
                find(func).or_else(|| args.iter().find_map(find))
            }
            Expr::Field { obj, .. } => find(obj),
            _ => None,
        }
    }
    fields
        .iter()
        .find(|(k, _)| k == "impl")
        .and_then(|(_, v)| find(v))
}

/// `test "run stays within budget"` → `run_stays_within_budget`.
fn slug(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut last_us = true; // collapse separators, trim leading
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
            last_us = false;
        } else if !last_us {
            out.push('_');
            last_us = true;
        }
    }
    while out.ends_with('_') {
        out.pop();
    }
    if out.is_empty() {
        "unnamed".into()
    } else {
        out
    }
}

/// First use keeps the bare slug; repeats get `_2`, `_3`, … so colliding
/// test names ("a b" / "a_b") both survive in the emitted module.
pub fn unique_slug(base: &str, used: &mut HashMap<String, usize>) -> String {
    let n = used.entry(base.to_string()).or_insert(0);
    *n += 1;
    if *n == 1 {
        base.to_string()
    } else {
        format!("{base}_{n}")
    }
}

fn is_builtin_type(n: &str) -> bool {
    matches!(n, "string" | "int" | "float" | "bool" | "none" | "()")
}

/// TypeExpr → JSON-Schema Python literal (design v1.3 §14).
fn schema_py(t: &TypeExpr, aliases: &HashSet<String>) -> String {
    match t {
        TypeExpr::Named(n) => match n.as_str() {
            "string" => "{\"type\": \"string\"}".into(),
            "int" => "{\"type\": \"integer\"}".into(),
            "float" => "{\"type\": \"number\"}".into(),
            "bool" => "{\"type\": \"boolean\"}".into(),
            "none" | "()" => "{\"type\": \"null\"}".into(),
            _ if aliases.contains(n) => n.clone(),
            _ => "{}".into(), // checker reports the unknown name (E0101)
        },
        TypeExpr::List(inner) => format!(
            "{{\"type\": \"array\", \"items\": {}}}",
            schema_py(inner, aliases)
        ),
        TypeExpr::Record(fs) => {
            let props: Vec<String> = fs
                .iter()
                .map(|(k, ft)| format!("\"{k}\": {}", schema_py(ft, aliases)))
                .collect();
            let req: Vec<String> = fs.iter().map(|(k, _)| format!("\"{k}\"")).collect();
            format!(
                "{{\"type\": \"object\", \"properties\": {{{}}}, \"required\": [{}]}}",
                props.join(", "),
                req.join(", ")
            )
        }
        TypeExpr::Refine(base, name, args) => {
            let extras: Vec<String> = match (name.as_str(), args.len()) {
                ("range", 2) => vec![
                    format!("\"minimum\": {}", py(&args[0], aliases)),
                    format!("\"maximum\": {}", py(&args[1], aliases)),
                ],
                ("format", 1) => {
                    let f = match &args[0] {
                        Expr::Ident(s) | Expr::Str(s) => s.as_str(),
                        _ => "url",
                    };
                    vec![format!(
                        "\"format\": \"{}\"",
                        if f == "url" { "uri" } else { f }
                    )]
                }
                _ => vec![],
            };
            match base.as_ref() {
                TypeExpr::Named(n) if is_builtin_type(n) => {
                    let base_pair = match n.as_str() {
                        "string" => "\"type\": \"string\"",
                        "int" => "\"type\": \"integer\"",
                        "float" => "\"type\": \"number\"",
                        "bool" => "\"type\": \"boolean\"",
                        _ => "\"type\": \"string\"",
                    };
                    let all = std::iter::once(base_pair.to_string())
                        .chain(extras)
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("{{{all}}}")
                }
                _ => {
                    let b = schema_py(base, aliases);
                    if extras.is_empty() {
                        b
                    } else {
                        format!("rt.extend({b}, {{{}}})", extras.join(", "))
                    }
                }
            }
        }
    }
}

/// A `schema:` option value (Ident / [Ident]) → schema literal.
fn expr_schema_py(e: &Expr, aliases: &HashSet<String>) -> String {
    match e {
        Expr::Ident(n) => schema_py(&TypeExpr::Named(n.clone()), aliases),
        Expr::ListLit(xs) if xs.len() == 1 => match &xs[0] {
            Expr::Ident(n) => schema_py(
                &TypeExpr::List(Box::new(TypeExpr::Named(n.clone()))),
                aliases,
            ),
            _ => "{}".into(),
        },
        _ => "{}".into(),
    }
}

/// f64 → a Python/TS float literal. Rust prints 1.0 as "1" — an INT literal
/// in the emitted code — so a bare integral value gains a trailing ".0".
pub fn fmt_f64(v: f64) -> String {
    let s = v.to_string();
    if s.contains('.') || s.contains('e') || s.contains("inf") || s.contains("NaN") {
        s
    } else {
        format!("{s}.0")
    }
}

fn py(e: &Expr, aliases: &HashSet<String>) -> String {
    match e {
        Expr::Int(v) => v.to_string(),
        Expr::Float(v) => fmt_f64(*v),
        Expr::Str(s) => py_str(s),
        Expr::Money(v, _unit) => format!("rt.USD(\"{v}\")"), // unit pre-checked (E0501)
        Expr::Bool(b) => {
            if *b {
                "True".into()
            } else {
                "False".into()
            }
        }
        Expr::None => "None".into(),
        Expr::Ident(n) => n.clone(),
        Expr::ListLit(xs) => {
            format!(
                "[{}]",
                xs.iter()
                    .map(|x| py(x, aliases))
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        }
        Expr::Prompt {
            body,
            interpolations,
        } => prompt_py(body, interpolations),
        Expr::LlmCall {
            prompt,
            options,
            repair,
        } => llm_py(false, prompt, options, *repair, aliases),
        Expr::Call { func, args, kwargs } => {
            let mut parts: Vec<String> = args.iter().map(|a| py(a, aliases)).collect();
            parts.extend(
                kwargs
                    .iter()
                    .map(|(k, v)| format!("{k}={}", py(v, aliases))),
            );
            // runtime-provided builtins get the rt. prefix; len is a real
            // Python builtin and passes through verbatim
            let f = match func.as_ref() {
                Expr::Ident(n) if matches!(n.as_str(), "replay" | "python" | "mcp" | "zip") => {
                    format!("rt.{n}")
                }
                other => py(other, aliases),
            };
            format!("{}({})", f, parts.join(", "))
        }
        Expr::Field { obj, name } => format!("{}.{name}", py(obj, aliases)),
        // always parenthesized: precedence is decided by the Nudge parser,
        // never re-decided by Python
        Expr::Binary { op, l, r } => {
            format!("({} {} {})", py(l, aliases), op_str(op), py(r, aliases))
        }
        Expr::Unary { op, x } => match op {
            BinOp::Sub => format!("(-{})", py(x, aliases)),
            _ => format!("(not {})", py(x, aliases)),
        },
        Expr::ParMap {
            coll,
            kwargs,
            params,
            body,
        } => {
            let mut s = format!(
                "rt.par_map({}, lambda {}: {}",
                py(coll, aliases),
                params.join(", "),
                py(body, aliases)
            );
            for (k, v) in kwargs {
                s.push_str(&format!(", {k}={}", py(v, aliases)));
            }
            s.push(')');
            s
        }
        Expr::ParAll(xs) => {
            format!(
                "rt.par_all([{}])",
                xs.iter()
                    .map(|x| py(x, aliases))
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        }
        Expr::ParRace(xs) => {
            format!(
                "rt.par_race([{}])",
                xs.iter()
                    .map(|x| py(x, aliases))
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        }
        // design §7: reducer join (dict union / list append-dedup at runtime)
        Expr::Merge { l, r } => format!("rt.merge({}, {})", py(l, aliases), py(r, aliases)),
        // design §4.4: route block — rt.route picks the first true arm
        Expr::Route { arms } => {
            let parts = arms
                .iter()
                .map(|(label, model, cond)| match cond {
                    Some(c) => format!(
                        "({}, {}, lambda: {})",
                        py_str(label),
                        py_str(model),
                        py(c, aliases)
                    ),
                    None => format!("({}, {}, None)", py_str(label), py_str(model)),
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!("rt.route({parts})")
        }
    }
}

fn prompt_py(body: &str, interps: &[String]) -> String {
    if interps.is_empty() {
        py_str(body)
    } else {
        // keys are the literal `{...}` contents; values are Python expressions
        // valid in the enclosing scope (identifiers / dotted paths at MVP)
        let mapping = interps
            .iter()
            .map(|k| format!("\"{k}\": {k}"))
            .collect::<Vec<_>>()
            .join(", ");
        format!("rt.render({}, {{{mapping}}})", py_str(body))
    }
}

fn llm_py(
    stream: bool,
    prompt: &Expr,
    options: &[(String, Expr)],
    repair: bool,
    aliases: &HashSet<String>,
) -> String {
    // NOTE: continuation lines are indented 8 spaces, assuming the call sits
    // directly under a single-depth body line (`return ...` / `x = ...`).
    let mut parts = vec![format!("prompt={}", py(prompt, aliases))];
    for (k, v) in options {
        match k.as_str() {
            "schema" => parts.push(format!("schema=rt.schema({})", expr_schema_py(v, aliases))),
            "model" => parts.push(format!("model={}", py(v, aliases))),
            "budget" => parts.push(format!("budget={}", py(v, aliases))),
            "retry" => parts.push(format!("retry={}", py(v, aliases))),
            "cache" => parts.push(match v {
                Expr::Ident(n) => format!("cache={}", py_str(n)),
                other => format!("cache={}", py(other, aliases)),
            }),
            "tags" => parts.push(format!("tags={}", py(v, aliases))),
            other => parts.push(format!(
                "# warning: unsupported option {other}={} (ignored)",
                py(v, aliases)
            )),
        }
    }
    if repair {
        parts.push("repair=True".into());
    }
    format!(
        "rt.{}(\n        {},\n    )",
        if stream { "llm_stream" } else { "llm_call" },
        parts.join(",\n        ")
    )
}

pub fn op_str(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::NotEq => "!=",
        BinOp::Lt => "<",
        BinOp::LtEq => "<=",
        BinOp::Gt => ">",
        BinOp::GtEq => ">=",
        BinOp::And => "and",
        BinOp::Or => "or",
        BinOp::Not => "not",
    }
}

/// Python string literal: escape the bare minimum, pass UTF-8 through verbatim.
fn py_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Shared `nudgec test` driver: load a generated module by path and run
/// every `nudge_test_*` function, reporting PASS/FAIL per test. Used by both
/// the `test` subcommand (main.rs) and the e2e tests below.
pub const TEST_DRIVER_PY: &str = r#"import importlib.util, sys, traceback
spec = importlib.util.spec_from_file_location("nudge_mod", "__MODULE__")
m = importlib.util.module_from_spec(spec)
spec.loader.exec_module(m)
fns = [getattr(m, n) for n in sorted(dir(m)) if n.startswith("nudge_test_")]
failed = 0
for f in fns:
    try:
        f()
        print("PASS", f.__name__)
    except Exception:
        failed += 1
        print("FAIL", f.__name__)
        traceback.print_exc()
print(f"{len(fns) - failed}/{len(fns)} tests passed")
sys.exit(1 if failed else 0)
"#;

#[cfg(test)]
mod tests;

