//! Nudge TypeScript codegen (design §14, v0.3c) — second backend.
//!
//! Emits a single `.ts` file importing `./nudge_runtime.ts`. MVP subset:
//! type aliases, tools, fns (let/return/assert), llm calls, merge, and the
//! expression forms; annotations are limited to simple TS names so tests
//! can erase them with a regex (see `strip_ts` in the tests). Deferred to
//! the full backend: `agent` blocks, `stream let` streaming, par
//! scheduling, and replay-driver tests — emitted as warning comments.

use crate::ast::*;
use std::collections::HashSet;

pub fn emit_ts(items: &[Item]) -> String {
    let aliases: HashSet<String> = items
        .iter()
        .filter_map(|i| match i {
            Item::TypeAlias { name, .. } => Some(name.clone()),
            _ => None,
        })
        .collect();

    let mut out = String::new();
    out.push_str("// Generated by nudgec 0.1.0 — do not edit.\nimport * as rt from \"./nudge_runtime.ts\";\n");
    let mut has_main = false;
    for item in items {
        out.push_str("\n\n");
        match item {
            Item::TypeAlias { name, ty } => {
                out.push_str(&format!("const {name} = rt.schema({});", schema_ts(ty, &aliases)));
            }
            Item::Fn { name, params, ret, body, .. } => {
                let ps = params
                    .iter()
                    .map(|p| format!("{}: {}", p.name, ty_ts(&p.ty, &aliases)))
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!("function {name}({ps}): {} {{\n", ty_ts(ret, &aliases)));
                out.push_str(&emit_body(body, &aliases));
                out.push_str("}");
                if name == "main" {
                    has_main = true;
                }
            }
            Item::Tool { name, params, fields, .. } => {
                let ps = params
                    .iter()
                    .map(|p| format!("{}: {}", p.name, ty_ts(&p.ty, &aliases)))
                    .collect::<Vec<_>>()
                    .join(", ");
                let arg_list = params.iter().map(|p| p.name.clone()).collect::<Vec<_>>().join(", ");
                let server = crate::codegen::impl_server(fields)
                    .map(|s| format!(", {{ server: {:?} }}", s))
                    .unwrap_or_default();
                out.push_str(&format!(
                    "function {name}({ps}): any {{\n  return rt.toolStub(\"{name}\", [{arg_list}]{server});\n}}"
                ));
            }
            Item::Test { name, body } => {
                out.push_str(&format!("function nudge_test_{}(): void {{\n", slug_ts(name)));
                out.push_str(&emit_body(body, &aliases));
                out.push_str("}");
            }
            Item::Agent { name, .. } => {
                // deferred: the TS backend does not lower agent state yet
                out.push_str(&format!(
                    "// warning: agent '{name}' skipped — the TS backend does not lower agent state yet (v0.3c MVP)"
                ));
            }
        }
    }
    if has_main {
        out.push_str("\n\nconst _result = main();\nif (_result !== undefined && _result !== null) console.log(_result);\n");
    }
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

fn emit_body(body: &[Stmt], aliases: &HashSet<String>) -> String {
    if body.is_empty() {
        return String::new();
    }
    let mut out = String::new();
    let last = body.len() - 1;
    for (i, st) in body.iter().enumerate() {
        let line = match st {
            Stmt::Let { name, value, stream, .. } => {
                if *stream {
                    format!("const {name} = {};  // warning: streaming not yet supported by the TS backend — plain call", ts(value, aliases))
                } else {
                    format!("const {name} = {};", ts(value, aliases))
                }
            }
            Stmt::StateWrite { field, .. } => {
                format!("// warning: state write 'state.{field}' skipped — agents are not yet supported by the TS backend")
            }
            Stmt::Assert(e) => format!("if (!({})) throw new Error(\"assertion failed\");", ts(e, aliases)),
            Stmt::ExprStmt(e) if i == last => format!("return {};", ts(e, aliases)),
            Stmt::ExprStmt(e) => format!("{};", ts(e, aliases)),
        };
        out.push_str("  ");
        out.push_str(&line);
        out.push('\n');
    }
    out
}

/// Nudge type → simple TS annotation (erasable: identifiers only).
fn ty_ts(t: &TypeExpr, aliases: &HashSet<String>) -> String {
    match t {
        TypeExpr::Named(n) => match n.as_str() {
            "string" => "string".into(),
            "int" | "float" => "number".into(),
            "bool" => "boolean".into(),
            "none" | "()" => "null".into(),
            _ if aliases.contains(n) => "any".into(),
            _ => "any".into(),
        },
        TypeExpr::List(_) => "any[]".into(),
        TypeExpr::Record(_) => "Record<string, any>".into(),
        TypeExpr::Refine(base, ..) => ty_ts(base, aliases),
    }
}

fn schema_ts(t: &TypeExpr, aliases: &HashSet<String>) -> String {
    match t {
        TypeExpr::Named(n) => match n.as_str() {
            "string" => "{\"type\": \"string\"}".into(),
            "int" => "{\"type\": \"integer\"}".into(),
            "float" => "{\"type\": \"number\"}".into(),
            "bool" => "{\"type\": \"boolean\"}".into(),
            "none" | "()" => "{\"type\": \"null\"}".into(),
            _ if aliases.contains(n) => n.clone(),
            _ => "{}".into(),
        },
        TypeExpr::List(inner) => format!("{{\"type\": \"array\", \"items\": {}}}", schema_ts(inner, aliases)),
        TypeExpr::Record(fs) => {
            let props: Vec<String> =
                fs.iter().map(|(k, ft)| format!("\"{k}\": {}", schema_ts(ft, aliases))).collect();
            let req: Vec<String> = fs.iter().map(|(k, _)| format!("\"{k}\"")).collect();
            format!(
                "{{\"type\": \"object\", \"properties\": {{{}}}, \"required\": [{}]}}",
                props.join(", "),
                req.join(", ")
            )
        }
        TypeExpr::Refine(base, name, args) => {
            let extras: Vec<String> = match (name.as_str(), args.len()) {
                ("range", 2) => vec![
                    format!("\"minimum\": {}", ts(&args[0], aliases)),
                    format!("\"maximum\": {}", ts(&args[1], aliases)),
                ],
                ("format", 1) => {
                    let f = match &args[0] {
                        Expr::Ident(s) | Expr::Str(s) => s.as_str(),
                        _ => "url",
                    };
                    vec![format!("\"format\": \"{}\"", if f == "url" { "uri" } else { f })]
                }
                _ => vec![],
            };
            match base.as_ref() {
                TypeExpr::Named(n) if matches!(n.as_str(), "string" | "int" | "float" | "bool" | "none" | "()") => {
                    let base_pair = match n.as_str() {
                        "string" => "\"type\": \"string\"",
                        "int" => "\"type\": \"integer\"",
                        "float" => "\"type\": \"number\"",
                        "bool" => "\"type\": \"boolean\"",
                        _ => "\"type\": \"string\"",
                    };
                    let all = std::iter::once(base_pair.to_string())
                        .chain(extras)
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("{{{all}}}")
                }
                _ => {
                    let b = schema_ts(base, aliases);
                    if extras.is_empty() {
                        b
                    } else {
                        format!("rt.extend({b}, {{{}}})", extras.join(", "))
                    }
                }
            }
        }
    }
}

fn expr_schema_ts(e: &Expr, aliases: &HashSet<String>) -> String {
    match e {
        Expr::Ident(n) => schema_ts(&TypeExpr::Named(n.clone()), aliases),
        Expr::ListLit(xs) if xs.len() == 1 => match &xs[0] {
            Expr::Ident(n) => {
                schema_ts(&TypeExpr::List(Box::new(TypeExpr::Named(n.clone()))), aliases)
            }
            _ => "{}".into(),
        },
        _ => "{}".into(),
    }
}

fn ts(e: &Expr, aliases: &HashSet<String>) -> String {
    match e {
        Expr::Int(v) => v.to_string(),
        Expr::Float(v) => v.to_string(),
        Expr::Str(s) => js_str(s),
        Expr::Money(v, _) => format!("rt.USD(\"{v}\")"),
        Expr::Bool(b) => if *b { "true".into() } else { "false".into() },
        Expr::None => "null".into(),
        Expr::Ident(n) => n.clone(),
        Expr::ListLit(xs) => {
            format!("[{}]", xs.iter().map(|x| ts(x, aliases)).collect::<Vec<_>>().join(", "))
        }
        Expr::Prompt { body, interpolations } => {
            if interpolations.is_empty() {
                js_str(body)
            } else {
                let mapping = interpolations
                    .iter()
                    .map(|k| format!("\"{k}\": {k}"))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("rt.render({}, {{{mapping}}})", js_str(body))
            }
        }
        Expr::LlmCall { prompt, options, repair } => llm_ts(prompt, options, *repair, aliases),
        Expr::Call { func, args, kwargs } => {
            let mut parts: Vec<String> = args.iter().map(|a| ts(a, aliases)).collect();
            parts.extend(kwargs.iter().map(|(k, v)| format!("{k}: {}", ts(v, aliases))));
            match func.as_ref() {
                Expr::Ident(n) if n == "len" => {
                    format!("({}.length)", ts(&args[0], aliases))
                }
                Expr::Ident(n) if matches!(n.as_str(), "replay" | "python" | "mcp" | "zip") => {
                    format!("rt.{n}({})", parts.join(", "))
                }
                other => format!("{}({})", ts(other, aliases), parts.join(", ")),
            }
        }
        Expr::Field { obj, name } => format!("{}.{name}", ts(obj, aliases)),
        Expr::Binary { op, l, r } => {
            let o = match op {
                BinOp::And => "&&",
                BinOp::Or => "||",
                other => crate::codegen::op_str(other),
            };
            format!("({} {} {})", ts(l, aliases), o, ts(r, aliases))
        }
        Expr::Unary { op, x } => match op {
            BinOp::Sub => format!("(-{})", ts(x, aliases)),
            _ => format!("(!{})", ts(x, aliases)),
        },
        Expr::ParMap { coll, kwargs, params, body } => {
            // MVP: sequential map (no worker pool in the TS runtime yet)
            let mut s = format!(
                "{}.map(({}) => {})",
                ts(coll, aliases),
                params.join(", "),
                ts(body, aliases)
            );
            if !kwargs.is_empty() {
                s.push_str("  // warning: par map kwargs ignored by the TS backend (sequential map)");
            }
            s
        }
        Expr::ParAll(xs) => {
            format!("Promise.all([{}])", xs.iter().map(|x| ts(x, aliases)).collect::<Vec<_>>().join(", "))
        }
        Expr::ParRace(xs) => {
            format!("Promise.race([{}])", xs.iter().map(|x| ts(x, aliases)).collect::<Vec<_>>().join(", "))
        }
        Expr::Merge { l, r } => format!("rt.merge({}, {})", ts(l, aliases), ts(r, aliases)),
    }
}

fn llm_ts(prompt: &Expr, options: &[(String, Expr)], repair: bool, aliases: &HashSet<String>) -> String {
    let mut parts = vec![format!("prompt: {}", ts(prompt, aliases))];
    for (k, v) in options {
        match k.as_str() {
            "schema" => parts.push(format!("schema: rt.schema({})", expr_schema_ts(v, aliases))),
            "model" => parts.push(format!("model: {}", ts(v, aliases))),
            "budget" => parts.push(format!("budget: {}", ts(v, aliases))),
            "retry" => parts.push(format!("retry: {}", ts(v, aliases))),
            "cache" => parts.push(match v {
                Expr::Ident(n) => format!("cache: {}", js_str(n)),
                other => format!("cache: {}", ts(other, aliases)),
            }),
            "tags" => parts.push(format!("tags: {}", ts(v, aliases))),
            other => parts.push(format!("/* warning: unsupported option {other} (ignored) */")),
        }
    }
    if repair {
        parts.push("repair: true".into());
    }
    format!("rt.llmCall({{{}}})", parts.join(", "))
}

/// `test "run stays within budget"` → `run_stays_within_budget`.
fn slug_ts(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut last_us = true;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
            last_us = false;
        } else if !last_us {
            out.push('_');
            last_us = true;
        }
    }
    while out.ends_with('_') {
        out.pop();
    }
    if out.is_empty() {
        "unnamed".into()
    } else {
        out
    }
}

/// JS string literal: escape the bare minimum, pass UTF-8 through verbatim.
fn js_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

// ── tests ────────────────────────────────────────────────────────────
#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::lex;
    use crate::parser::parse;

    fn gen_ts(src: &str) -> String {
        emit_ts(&parse(lex(src).unwrap()).unwrap())
    }

    /// Erase the simple annotation forms the emitter produces (test-only;
    /// lets node run the output without a TS toolchain). Dependency-free:
    /// scans for `: <SimpleTy>` followed by one of `, ) { = ; <space>`.
    fn strip_ts(code: &str) -> String {
        const TYS: [&str; 8] = [
            "Record<string, any>", "string", "number", "boolean", "null", "any[]", "any", "void",
        ];
        let mut out = String::with_capacity(code.len());
        let mut rest = code;
        while let Some(pos) = rest.find(": ") {
            let after = &rest[pos + 2..];
            let hit = TYS.iter().find_map(|t| {
                after
                    .strip_prefix(t)
                    .filter(|a2| a2.starts_with([',', ')', '{', '=', ';', ' ']))
                    .map(|_| t)
            });
            match hit {
                Some(t) => {
                    out.push_str(&rest[..pos]);
                    rest = &after[t.len()..];
                }
                None => {
                    out.push_str(&rest[..pos + 2]);
                    rest = after;
                }
            }
        }
        out.push_str(rest);
        out
    }

    #[test]
    fn ts_hello_llm_shape() {
        let out = gen_ts(include_str!("../../../examples/hello_llm.ndg"));
        assert!(out.contains("import * as rt from \"./nudge_runtime.ts\";"), "got:\n{out}");
        assert!(out.contains("function main(): string {"), "got:\n{out}");
        assert!(out.contains("return rt.llmCall({prompt: \"Say hello to the Nudge language in one short sentence.\", model: \"anthropic:sonnet-4.6\", budget: rt.USD(\"0.01\")});"), "got:\n{out}");
    }

    #[test]
    fn ts_types_tools_and_merge() {
        let src = "type F = { claim: string }\ntool search(q: string) -> [F] { impl: mcp(\"s\").web(q) side_effects: none }\nfn f(q: string) -> [F] uses LLM { let a = llm\"\"\"c {q}\"\"\" with { schema: [F], model: \"m\" }\n    a | merge a }";
        let out = gen_ts(src);
        assert!(out.contains("const F = rt.schema({\"type\": \"object\", \"properties\": {\"claim\": {\"type\": \"string\"}}, \"required\": [\"claim\"]});"), "got:\n{out}");
        assert!(out.contains("return rt.toolStub(\"search\", [q], { server: \"s\" });"), "got:\n{out}");
        assert!(out.contains("schema: rt.schema({\"type\": \"array\", \"items\": F})"), "got:\n{out}");
        assert!(out.contains("return rt.merge(a, a);"), "got:\n{out}");
        assert!(out.contains("function f(q: string): any[] {"), "got:\n{out}");
        assert_eq!(strip_ts("function f(q: string): any[] {"), "function f(q) {");
    }

    #[test]
    fn ts_agent_and_stream_warn() {
        let src = "agent A {\n    state {\n        n: int = 0,\n    }\n    fn step() -> int { 0 }\n}";
        let out = gen_ts(src);
        assert!(out.contains("warning: agent 'A' skipped"), "got:\n{out}");
        let src2 = "fn f() -> string uses LLM { stream let t: string = llm\"\"\"x\"\"\" with { model: \"m\" }\n    t }";
        let out2 = gen_ts(src2);
        assert!(out2.contains("warning: streaming not yet supported by the TS backend"), "got:\n{out2}");
    }

    // ── end-to-end (skipped without node / runtime checkout) ──────

    #[test]
    fn ts_hello_runs_under_node() {
        use std::process::Command;
        if Command::new("node").arg("--version").output().is_err() {
            return;
        }
        let runtime = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../runtime");
        if !runtime.exists() {
            return;
        }
        let dir = std::env::temp_dir().join(format!("nudge_tse2e_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        // the emitted .ts is annotation-stripped so plain node can run it;
        // the runtime ships plain JS and only needs the rename
        let emitted = strip_ts(&gen_ts(include_str!("../../../examples/hello_llm.ndg")))
            .replace("./nudge_runtime.ts", "./nudge_runtime.mjs");
        std::fs::write(dir.join("hello.mjs"), emitted).unwrap();
        let rt_src = std::fs::read_to_string(runtime.join("nudge_runtime.ts")).unwrap();
        std::fs::write(dir.join("nudge_runtime.mjs"), rt_src).unwrap();
        let out = Command::new("node")
            .arg(dir.join("hello.mjs"))
            .env("NUDGE_PROVIDER", "fake")
            .env("NUDGE_TRACE", dir.join("trace.jsonl"))
            .current_dir(&dir)
            .output()
            .unwrap();
        assert!(out.status.success(), "stderr: {}", String::from_utf8_lossy(&out.stderr));
        let stdout = String::from_utf8_lossy(&out.stdout);
        assert!(stdout.contains("[fake:anthropic:sonnet-4.6]"), "stdout: {stdout}");
        let log = std::fs::read_to_string(dir.join("trace.jsonl")).unwrap();
        assert!(log.contains("\"kind\":\"llm.call\"") || log.contains("\"kind\": \"llm.call\""), "trace: {log}");
    }
}
