//! `nudgec mcp` (D2): expose a program's functions as MCP tools over
//! stdio (JSON-RPC 2.0, MCP protocol 2024-11-05). Other agents — Claude,
//! Cursor, anything MCP-speaking — can then call Nudge's typed decision
//! functions as tools. Stdlib-only on both sides (the driver uses plain
//! Python; the compiler only writes the driver).

pub const MCP_PY: &str = r#""""Generated by nudgec — MCP stdio server, do not edit."""
import importlib.util, inspect, json, sys

spec = importlib.util.spec_from_file_location("nudge_mod", "__MODULE__")
m = importlib.util.module_from_spec(spec)
spec.loader.exec_module(m)

INCLUDE = "__FNS__".split(",") if "__FNS__" else None


def _plain(v):
    if isinstance(v, dict):
        return {k: _plain(x) for k, x in v.items()}
    if isinstance(v, (list, tuple)):
        return [_plain(x) for x in v]
    if hasattr(v, "__dict__") and not isinstance(v, type):
        return {k: _plain(x) for k, x in vars(v).items()}
    return v


def _tools():
    out = []
    for name in sorted(dir(m)):
        if name.startswith("_") or name.startswith("nudge_test_"):
            continue
        if INCLUDE and name not in INCLUDE:
            continue
        fn = getattr(m, name)
        if not callable(fn) or not hasattr(fn, "__code__"):
            continue
        # generated fns are *args wrappers — param names aren't recoverable,
        # so the schema uses the same `input` contract as nudgec serve/eval
        out.append({
            "name": name,
            "description": (inspect.getdoc(fn) or f"Nudge function '{name}'").strip(),
            "inputSchema": {
                "type": "object",
                "properties": {
                    "input": {
                        "description": "state text, or a JSON array of positional arguments",
                        "type": ["string", "array"],
                    }
                },
                "required": ["input"],
            },
        })
    return out


def _reply(rid, result):
    sys.stdout.write(json.dumps({"jsonrpc": "2.0", "id": rid, "result": result}) + "\n")
    sys.stdout.flush()


while True:
    line = sys.stdin.readline()
    if not line:
        break
    line = line.strip()
    if not line:
        continue
    try:
        msg = json.loads(line)
    except json.JSONDecodeError:
        continue
    method = msg.get("method", "")
    rid = msg.get("id")
    if method == "initialize":
        _reply(rid, {
            "protocolVersion": "2024-11-05",
            "capabilities": {"tools": {}},
            "serverInfo": {"name": "nudge", "version": "__VERSION__"},
        })
    elif method == "tools/list":
        _reply(rid, {"tools": _tools()})
    elif method == "tools/call":
        name = msg.get("params", {}).get("name", "")
        args = msg.get("params", {}).get("arguments", {}) or {}
        fn = getattr(m, name, None)
        if fn is None or not callable(fn):
            _reply(rid, {"content": [{"type": "text", "text": f"unknown tool '{name}'"}], "isError": True})
            continue
        try:
            inp = args.get("input")
            pos = inp if isinstance(inp, list) else [inp]
            result = _plain(fn(*pos))
            _reply(rid, {"content": [{"type": "text", "text": json.dumps(result, ensure_ascii=False, default=str)}]})
        except Exception as e:
            _reply(rid, {"content": [{"type": "text", "text": f"{type(e).__name__}: {e}"}], "isError": True})
    elif rid is not None:
        _reply(rid, {})
"#;

/// Returns the driver source for `file`'s emitted module.
pub fn driver(module_path: &str, version: &str, fns: &str) -> String {
    MCP_PY
        .replace("__MODULE__", module_path)
        .replace("__VERSION__", version)
        .replace("__FNS__", fns)
}
