//! `nudgec serve` (D1): run a program's function as a local HTTP API —
//! stdlib `http.server` only (the runtime is dependency-free, so the
//! server must be too). POST /run {input | input: [args]} →
//! {ok, result | error}; GET /health. Traces/proxies behave exactly as
//! in a normal run because the emitted module is the real program.

pub const SERVER_PY: &str = r#""""Generated by nudgec — HTTP server, do not edit."""
import importlib.util, json
from http.server import BaseHTTPRequestHandler, HTTPServer

spec = importlib.util.spec_from_file_location("nudge_mod", "__MODULE__")
m = importlib.util.module_from_spec(spec)
spec.loader.exec_module(m)
FN_NAME = "__FN__"
PORT = __PORT__


def _plain(v):
    if isinstance(v, dict):
        return {k: _plain(x) for k, x in v.items()}
    if isinstance(v, (list, tuple)):
        return [_plain(x) for x in v]
    if hasattr(v, "__dict__") and not isinstance(v, type):
        return {k: _plain(x) for k, x in vars(v).items()}
    return v


fn = getattr(m, FN_NAME, None)
if fn is None or not callable(fn):
    raise SystemExit(f"error: no callable function '{FN_NAME}' in the program")


class H(BaseHTTPRequestHandler):
    def log_message(self, *a):
        pass

    def _json(self, code, payload):
        body = json.dumps(payload, ensure_ascii=False, default=str).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        if self.path == "/health":
            self._json(200, {"ok": True, "fn": FN_NAME})
        else:
            self.send_error(404)

    def do_POST(self):
        if self.path != "/run":
            self.send_error(404)
            return
        try:
            n = int(self.headers.get("Content-Length", 0))
        except (ValueError, TypeError):
            n = 0
        try:
            req = json.loads(self.rfile.read(n) or b"{}")
        except Exception as e:
            self._json(400, {"ok": False, "error": f"bad JSON: {e}"})
            return
        args = [] if "input" not in req else (req["input"] if isinstance(req["input"], list) else [req["input"]])
        try:
            self._json(200, {"ok": True, "result": _plain(fn(*args))})
        except Exception as e:
            self._json(500, {"ok": False, "error": f"{type(e).__name__}: {e}"})


print(f"serving {FN_NAME} on http://127.0.0.1:{PORT}  (POST /run, GET /health)")
HTTPServer(("127.0.0.1", PORT), H).serve_forever()
"#;
