use super::*;
use crate::lexer::lex;
use crate::parser::parse;

fn gen(src: &str) -> String {
    emit(&parse(lex(src).unwrap()).unwrap())
}

#[test]
fn hello_llm_golden() {
    let src = include_str!("../../../../examples/hello_llm.ndg");
    let expected = "\"\"\"Generated by nudgec 0.1.0 — do not edit.\"\"\"\nimport nudge_runtime as rt\n\n\n@rt.effectful(effects={\"LLM\"})\ndef main():\n    return rt.llm_call(\n        prompt=\"Say hello to the Nudge language in one short sentence.\",\n        model=\"anthropic:sonnet-4.6\",\n        budget=rt.USD(\"0.01\"),\n    )\n\n\nif __name__ == \"__main__\":\n    _result = main()\n    if _result is not None:\n        print(_result)\n";
    assert_eq!(gen(src), expected);
}

#[test]
fn llm_options_and_interpolation() {
    let src = "fn f(q: string) -> string uses LLM {\n    llm\"\"\"hi {q}\"\"\"\n    with { model: \"m\", retry: 2 with repair, cache: content_addressed, tags: [\"a\", \"b\"] }\n}";
    let out = gen(src);
    assert!(out.contains("prompt=rt.render(\"hi {q}\", {\"q\": q}),"), "got:\n{out}");
    assert!(out.contains("retry=2,"), "got:\n{out}");
    assert!(out.contains("repair=True,"), "got:\n{out}");
    assert!(out.contains("cache=\"content_addressed\","), "got:\n{out}");
    assert!(out.contains("tags=[\"a\", \"b\"],"), "got:\n{out}");
}

#[test]
fn type_alias_lowers_to_schema_literal() {
    let src = "type Url = string @format(url)\ntype Finding = { claim: string, confidence: float @range(0, 1) }";
    let out = gen(src);
    assert!(out.contains("Url = rt.schema({\"type\": \"string\", \"format\": \"uri\"})"), "got:\n{out}");
    assert!(
        out.contains("Finding = rt.schema({\"type\": \"object\", \"properties\": {\"claim\": {\"type\": \"string\"}, \"confidence\": {\"type\": \"number\", \"minimum\": 0, \"maximum\": 1}}, \"required\": [\"claim\", \"confidence\"]})"),
        "got:\n{out}"
    );
}

#[test]
fn schema_option_lowers_to_rt_schema() {
    let src = "type Finding = { claim: string }\nfn f() -> [Finding] uses LLM { llm\"\"\"x\"\"\" with { schema: [Finding] } }";
    let out = gen(src);
    assert!(out.contains("schema=rt.schema({\"type\": \"array\", \"items\": Finding})"), "got:\n{out}");
}

#[test]
fn tool_lowers_to_stub_fn() {
    let src = "tool web_search(q: string) -> [R] { impl: mcp(\"s\").web(q) side_effects: none }";
    let out = gen(src);
    assert!(out.contains("def web_search(q):\n    return rt.tool_stub(\"web_search\", [q], server=\"s\")"), "got:\n{out}");
}

#[test]
fn stream_let_lowers_to_llm_stream() {
    let src = "fn f() -> string uses LLM { stream let t: string = llm\"\"\"x\"\"\" with { model: \"m\" }\n    t }";
    let out = gen(src);
    assert!(out.contains("t = rt.llm_stream("), "got:\n{out}");
    assert!(!out.contains("t = rt.llm_call("), "got:\n{out}");
    // stream on a non-llm binding degrades to a plain let with a warning
    let src2 = "fn f() -> int { stream let n = 3\n    n }";
    let out2 = gen(src2);
    assert!(out2.contains("n = 3  # warning: stream ignored on non-llm binding"), "got:\n{out2}");
}

#[test]
fn agent_lowers_to_checkpointed_state() {
    let src = "agent A {\n    state {\n        notes: [string] = [],\n        round: int = 0,\n    }\n    fn step(q: string) -> int uses LLM {\n        let r = llm\"\"\"next: {q}\"\"\" with { model: \"m\" }\n        state.notes += [r]\n        state.round = state.round + 1\n        state.round\n    }\n}";
    let out = gen(src);
    assert!(out.contains("_state_A = rt.AgentState(\"A\", {\"notes\": [], \"round\": 0})"), "got:\n{out}");
    assert!(out.contains("def step(q):"), "got:\n{out}");
    assert!(out.contains("_state_A.notes += [r]"), "got:\n{out}");
    assert!(out.contains("_state_A.round = (_state_A.round + 1)"), "got:\n{out}");
    assert!(out.contains("return _state_A.round"), "got:\n{out}");
}

#[test]
fn merge_lowers_to_rt_merge() {
    let src = "agent A {\n    state {\n        found: [string] = [],\n    }\n    fn step(s: string) -> [string] {\n        state.found = state.found | merge [s]\n        state.found\n    }\n}";
    let out = gen(src);
    assert!(out.contains("_state_A.found = rt.merge(_state_A.found, [s])"), "got:\n{out}");
}

#[test]
fn route_block_lowers_to_rt_route() {
    let src = "fn f(b: bool) -> string uses LLM { llm\"\"\"x\"\"\" with { model: route{ cheap: \"m1\" when b, strong: \"m2\" otherwise } } }";
    let out = gen(src);
    assert!(out.contains("model=rt.route((\"cheap\", \"m1\", lambda: b), (\"strong\", \"m2\", None))"), "got:\n{out}");
}

#[test]
fn par_map_lowers_to_runtime_call() {
    let src = "fn f(angles: [string]) -> [string] { let h = par map angles |a| -> search(a) }";
    assert!(gen(src).contains("h = rt.par_map(angles, lambda a: search(a))"));
    let src = "fn f(angles: [string], hits: [string]) -> [string] { let f2 = par map(angles zip hits, concurrency = 3) |(a, h)| -> analyze(a, h) }";
    assert!(gen(src).contains("rt.par_map(zip(angles, hits), lambda a, h: analyze(a, h), concurrency=3)"));
}

// ── end-to-end (skipped without python3 / runtime checkout) ──────

struct E2e {
    dir: std::path::PathBuf,
    runtime: std::path::PathBuf,
}

fn e2e(name: &str) -> Option<E2e> {
    use std::process::Command;
    if Command::new("python3").arg("--version").output().is_err() {
        return None;
    }
    let runtime = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../runtime");
    if !runtime.exists() {
        return None;
    }
    // unique dir per test: `cargo test` runs them in parallel threads
    let dir = std::env::temp_dir().join(format!("nudge_e2e_{}_{}", std::process::id(), name));
    std::fs::create_dir_all(&dir).unwrap();
    Some(E2e { dir, runtime })
}

fn run_py(e: &E2e, file: &std::path::Path, extra: &[(&str, &str)]) -> std::process::Output {
    use std::process::Command;
    let mut cmd = Command::new("python3");
    cmd.arg(file)
        .env("NUDGE_PROVIDER", "fake")
        .env("NUDGE_TRACE", e.dir.join("trace.jsonl"))
        .env("PYTHONPATH", &e.runtime)
        // hermetic cwd: run-local state (.nudge/) lands in the test dir
        .current_dir(&e.dir);
    for (k, v) in extra {
        cmd.env(k, v);
    }
    cmd.output().unwrap()
}

#[test]
fn hello_llm_runs_under_fake_provider() {
    let Some(e) = e2e("hello") else { return };
    let py = gen(include_str!("../../../../examples/hello_llm.ndg"));
    let out_py = e.dir.join("hello_llm.py");
    std::fs::write(&out_py, py).unwrap();
    let output = run_py(&e, &out_py, &[]);
    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("[fake:anthropic:sonnet-4.6]"), "stdout: {stdout}");
    let log = std::fs::read_to_string(e.dir.join("trace.jsonl")).unwrap();
    assert!(log.contains("\"kind\": \"llm.call\""), "trace: {log}");
}

#[test]
fn research_agent_runs_end_to_end() {
    let Some(e) = e2e("agent") else { return };
    let py = gen(include_str!("../../../../examples/research_agent.ndg"));
    let out_py = e.dir.join("research_agent.py");
    std::fs::write(&out_py, py).unwrap();
    let driver = e.dir.join("drive_agent.py");
    std::fs::write(
        &driver,
        format!(
            "import sys\nsys.path.insert(0, {:?})\nimport research_agent as r\nresult = r.run(\"urban heat islands\")\nprint(\"OK\", sorted(result.keys()))\n",
            e.dir.to_string_lossy()
        ),
    )
    .unwrap();
    let output = run_py(&e, &driver, &[]);
    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("OK") && stdout.contains("findings"), "stdout: {stdout}");
    let log = std::fs::read_to_string(e.dir.join("trace.jsonl")).unwrap();
    let calls = log.lines().filter(|l| l.contains("\"llm.call\"")).count();
    // fake provider plans 3 angles: 1 plan + 3 analyze + 1 merge
    assert_eq!(calls, 5, "expected 5 llm.call records, trace: {log}");
}

#[test]
fn repair_round_recovers_from_schema_violation() {
    let Some(e) = e2e("repair") else { return };
    let src = "type T = { title: string }\nfn main() -> T uses LLM {\n    llm\"\"\"give me a title\"\"\" with { schema: T, model: \"m\", retry: 2 with repair }\n}";
    let out_py = e.dir.join("repair_demo.py");
    std::fs::write(&out_py, gen(src)).unwrap();
    let output = run_py(&e, &out_py, &[("NUDGE_FAKE_FAIL_FIRST", "1")]);
    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    assert!(String::from_utf8_lossy(&output.stdout).contains("title"), "stdout: {output:?}");
    let log = std::fs::read_to_string(e.dir.join("trace.jsonl")).unwrap();
    assert!(log.contains("schema_violation"), "trace: {log}");
    assert!(log.contains("\"repair_round\": 1"), "trace: {log}");
}

#[test]
fn exhausted_repairs_raise_schema_failure() {
    let Some(e) = e2e("fail") else { return };
    let src = "type T = { title: string }\nfn main() -> T uses LLM {\n    llm\"\"\"give me a title\"\"\" with { schema: T, model: \"m\", retry: 2 with repair }\n}";
    let out_py = e.dir.join("fail_demo.py");
    std::fs::write(&out_py, gen(src)).unwrap();
    let output = run_py(&e, &out_py, &[("NUDGE_FAKE_FAIL_FIRST", "99")]);
    assert!(!output.status.success(), "expected failure, stdout: {}", String::from_utf8_lossy(&output.stdout));
    assert!(String::from_utf8_lossy(&output.stderr).contains("SchemaFailure"), "stderr: {}", String::from_utf8_lossy(&output.stderr));
}

// ── day 9–10: test blocks + replay ─────────────────────────────

#[test]
fn test_block_lowers_to_runnable_fn() {
    let src = "test \"stays within budget!\" { let t = replay(\"traces/x.jsonl\")\nassert t.cost_usd < 0.25 }";
    let out = gen(src);
    assert!(out.contains("def nudge_test_stays_within_budget():"), "got:\n{out}");
    assert!(out.contains("t = rt.replay(\"traces/x.jsonl\")"), "got:\n{out}");
    assert!(out.contains("assert (t.cost_usd < 0.25)"), "got:\n{out}");
}

#[test]
fn slug_edge_cases() {
    assert_eq!(slug("run stays within budget on recorded trace"), "run_stays_within_budget_on_recorded_trace");
    assert_eq!(slug("!!weird — NA ME!!"), "weird_na_me");
    assert_eq!(slug(""), "unnamed");
}

#[test]
fn test_block_runs_against_recorded_trace() {
    let Some(e) = e2e("testrun") else { return };
    // research_agent.ndg's own test block replays traces/demo_run.jsonl
    let py = gen(include_str!("../../../../examples/research_agent.ndg"));
    let out_py = e.dir.join("research_agent.py");
    std::fs::write(&out_py, py).unwrap();
    std::fs::create_dir_all(e.dir.join("traces")).unwrap();

    // 1. record a real run into traces/demo_run.jsonl
    let rec = e.dir.join("record.py");
    std::fs::write(
        &rec,
        format!("import sys\nsys.path.insert(0, {:?})\nimport research_agent as r\nr.run(\"urban heat islands\")\n", e.dir.to_string_lossy()),
    )
    .unwrap();
    let trace_path = e.dir.join("traces/demo_run.jsonl");
    let output = run_py(&e, &rec, &[("NUDGE_TRACE", trace_path.to_str().unwrap())]);
    assert!(output.status.success(), "record stderr: {}", String::from_utf8_lossy(&output.stderr));
    let log = std::fs::read_to_string(&trace_path).unwrap();
    assert!(log.contains("\"fn.return\""), "trace needs a fn.return record: {log}");

    // 2. run the generated nudge_test_* functions with cwd = e.dir
    //    (so the relative trace path in the test block resolves)
    let driver = e.dir.join("run_tests.py");
    std::fs::write(&driver, TEST_DRIVER_PY.replace("__MODULE__", &out_py.to_string_lossy())).unwrap();
    let output = std::process::Command::new("python3")
        .arg(&driver)
        .current_dir(&e.dir)
        .env("PYTHONPATH", &e.runtime)
        .output()
        .unwrap();
    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("PASS nudge_test_run_stays_within_budget_on_recorded_trace"), "stdout: {stdout}");
}

#[test]
fn replay_mode_reproduces_outputs_without_provider() {
    let Some(e) = e2e("replay") else { return };
    let py = gen(include_str!("../../../../examples/research_agent.ndg"));
    let out_py = e.dir.join("research_agent.py");
    std::fs::write(&out_py, py).unwrap();
    let driver = e.dir.join("drive.py");
    std::fs::write(
        &driver,
        format!("import sys, json\nsys.path.insert(0, {:?})\nimport research_agent as r\nprint(json.dumps(r.run(\"urban heat islands\"), sort_keys=True))\n", e.dir.to_string_lossy()),
    )
    .unwrap();
    // live run
    let trace1 = e.dir.join("t1.jsonl");
    let out1 = run_py(&e, &driver, &[("NUDGE_TRACE", trace1.to_str().unwrap())]);
    assert!(out1.status.success(), "stderr: {}", String::from_utf8_lossy(&out1.stderr));
    // full replay of that trace: zero provider calls, zero new llm.call records
    let trace2 = e.dir.join("t2.jsonl");
    let out2 = run_py(
        &e,
        &driver,
        &[("NUDGE_TRACE", trace2.to_str().unwrap()), ("NUDGE_REPLAY", trace1.to_str().unwrap())],
    );
    assert!(out2.status.success(), "stderr: {}", String::from_utf8_lossy(&out2.stderr));
    assert_eq!(out1.stdout, out2.stdout, "replay must reproduce the live result");
    let log2 = std::fs::read_to_string(&trace2).unwrap_or_default();
    assert!(!log2.contains("\"llm.call\""), "replay must not call any provider: {log2}");
}

#[test]
fn replay_version_mismatch_raises() {
    let Some(e) = e2e("version") else { return };
    let bad = e.dir.join("bad.jsonl");
    std::fs::write(&bad, "{\"v\": 99, \"seq\": 1, \"kind\": \"llm.call\"}\n").unwrap();
    let driver = e.dir.join("drive_v.py");
    std::fs::write(&driver, format!("import nudge_runtime as rt\nrt.replay({:?})\n", bad.to_string_lossy())).unwrap();
    let output = std::process::Command::new("python3")
        .arg(&driver)
        .env("PYTHONPATH", &e.runtime)
        .output()
        .unwrap();
    assert!(!output.status.success(), "expected failure");
    assert!(String::from_utf8_lossy(&output.stderr).contains("ReplayMismatch"), "stderr: {}", String::from_utf8_lossy(&output.stderr));
}

// ── day 11–12: budget + parallel scheduler ─────────────────────

#[test]
fn run_budget_wall_stops_the_run() {
    let Some(e) = e2e("budget") else { return };
    // research agent makes 5 llm calls × $0.001 fake price; $0.0025
    // covers exactly two, so the third hits the run-level wall
    let py = gen(include_str!("../../../../examples/research_agent.ndg"));
    let out_py = e.dir.join("research_agent.py");
    std::fs::write(&out_py, py).unwrap();
    let driver = e.dir.join("drive_b.py");
    std::fs::write(
        &driver,
        format!("import sys\nsys.path.insert(0, {:?})\nimport research_agent as r\nr.run(\"urban heat islands\")\n", e.dir.to_string_lossy()),
    )
    .unwrap();
    let output = run_py(&e, &driver, &[("NUDGE_BUDGET", "0.0025")]);
    assert!(!output.status.success(), "expected BudgetExceeded, stdout: {}", String::from_utf8_lossy(&output.stdout));
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("BudgetExceeded"), "stderr: {stderr}");
    // the trace is complete up to the crash point (design §11). The 3
    // analyze calls fan out concurrently, so 2–3 of them start (and are
    // traced) before the shared counter crosses the wall
    let log = std::fs::read_to_string(e.dir.join("trace.jsonl")).unwrap();
    let calls = log.lines().filter(|l| l.contains("\"llm.call\"")).count();
    assert!((3..=4).contains(&calls), "expected 3–4 llm.call records before the wall, trace: {log}");
}

#[test]
fn per_call_budget_wall() {
    let Some(e) = e2e("callbudget") else { return };
    let src = "fn main() -> string uses LLM {\n    llm\"\"\"hi\"\"\" with { model: \"m\", budget: 0.0005 USD }\n}";
    let out_py = e.dir.join("call_budget.py");
    std::fs::write(&out_py, gen(src)).unwrap();
    let output = run_py(&e, &out_py, &[]);
    assert!(!output.status.success(), "expected BudgetExceeded");
    assert!(String::from_utf8_lossy(&output.stderr).contains("BudgetExceeded"), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    // an ample per-call budget passes
    let src2 = "fn main() -> string uses LLM {\n    llm\"\"\"hi\"\"\" with { model: \"m\", budget: 0.01 USD }\n}";
    let out_py2 = e.dir.join("call_budget_ok.py");
    std::fs::write(&out_py2, gen(src2)).unwrap();
    let output2 = run_py(&e, &out_py2, &[]);
    assert!(output2.status.success(), "stderr: {}", String::from_utf8_lossy(&output2.stderr));
}

#[test]
fn par_map_is_concurrent_and_order_preserving() {
    let Some(e) = e2e("par") else { return };
    let driver = e.dir.join("drive_par.py");
    std::fs::write(
        &driver,
        "import time\nimport nudge_runtime as rt\nstart = time.time()\ndef slow(x):\n    time.sleep(0.05)\n    return x * 10\nout = rt.par_map(range(6), slow, concurrency=3)\nelapsed = time.time() - start\nassert out == [0, 10, 20, 30, 40, 50], out\nassert elapsed < 0.15, f\"not concurrent: {elapsed}\"\n# pair-unpacking still works through the pool\npairs = rt.par_map(zip([1, 2], [3, 4]), lambda a, b: a + b)\nassert pairs == [4, 6], pairs\n# race returns a result\nwinner = rt.par_race([lambda: 'a', lambda: 'b'])\nassert winner in ('a', 'b')\nprint(\"PAR OK\")\n",
    )
    .unwrap();
    let output = run_py(&e, &driver, &[]);
    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    assert!(String::from_utf8_lossy(&output.stdout).contains("PAR OK"));
}

#[test]
fn par_branches_share_the_run_budget() {
    let Some(e) = e2e("parbudget") else { return };
    // 4 parallel llm calls × $0.001 against a $0.0025 run budget
    let driver = e.dir.join("drive_pb.py");
    std::fs::write(
        &driver,
        "import nudge_runtime as rt\nrt.par_map(range(4), lambda i: rt.llm_call(prompt=f\"q{i}\", model=\"m\"), concurrency=4)\n",
    )
    .unwrap();
    let output = run_py(&e, &driver, &[("NUDGE_BUDGET", "0.0025")]);
    assert!(!output.status.success(), "expected BudgetExceeded from an in-flight branch");
    assert!(String::from_utf8_lossy(&output.stderr).contains("BudgetExceeded"), "stderr: {}", String::from_utf8_lossy(&output.stderr));
}

// ── v0.2: hybrid replay (design §6.2) ──────────────────────────

#[test]
fn live_run_traces_tool_calls() {
    let Some(e) = e2e("tooltrace") else { return };
    let py = gen(include_str!("../../../../examples/research_agent.ndg"));
    let out_py = e.dir.join("research_agent.py");
    std::fs::write(&out_py, py).unwrap();
    let driver = e.dir.join("drive_t.py");
    std::fs::write(
        &driver,
        format!("import sys\nsys.path.insert(0, {:?})\nimport research_agent as r\nr.run(\"urban heat islands\")\n", e.dir.to_string_lossy()),
    )
    .unwrap();
    let output = run_py(&e, &driver, &[]);
    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    let log = std::fs::read_to_string(e.dir.join("trace.jsonl")).unwrap();
    let tools = log.lines().filter(|l| l.contains("\"tool.call\"")).count();
    assert_eq!(tools, 3, "expected 3 tool.call records (one per angle), trace: {log}");
    assert!(log.contains("\"tool\": \"web_search\""), "trace: {log}");
    // seq stays unique even though tool calls fan out on a thread pool
    let mut seqs: Vec<u64> = log
        .lines()
        .filter_map(|l| l.split("\"seq\": ").nth(1)?.split(',').next()?.trim().parse().ok())
        .collect();
    seqs.sort_unstable();
    seqs.dedup();
    assert_eq!(seqs.len(), log.lines().count(), "duplicate seq in trace: {log}");
}

#[test]
fn hybrid_replay_runs_tools_live_but_not_llm() {
    let Some(e) = e2e("hybrid") else { return };
    let py = gen(include_str!("../../../../examples/research_agent.ndg"));
    let out_py = e.dir.join("research_agent.py");
    std::fs::write(&out_py, py).unwrap();
    let driver = e.dir.join("drive_h.py");
    std::fs::write(
        &driver,
        format!("import sys, json\nsys.path.insert(0, {:?})\nimport research_agent as r\nprint(json.dumps(r.run(\"urban heat islands\"), sort_keys=True))\n", e.dir.to_string_lossy()),
    )
    .unwrap();
    // 1. record a live run
    let t1 = e.dir.join("t1.jsonl");
    let out1 = run_py(&e, &driver, &[("NUDGE_TRACE", t1.to_str().unwrap())]);
    assert!(out1.status.success(), "stderr: {}", String::from_utf8_lossy(&out1.stderr));
    // 2. hybrid replay: llm from trace, tools live
    let t2 = e.dir.join("t2.jsonl");
    let out2 = run_py(
        &e,
        &driver,
        &[
            ("NUDGE_TRACE", t2.to_str().unwrap()),
            ("NUDGE_REPLAY", t1.to_str().unwrap()),
            ("NUDGE_REPLAY_MODE", "llm"),
        ],
    );
    assert!(out2.status.success(), "stderr: {}", String::from_utf8_lossy(&out2.stderr));
    assert_eq!(out1.stdout, out2.stdout, "hybrid replay must reproduce the result");
    let log2 = std::fs::read_to_string(&t2).unwrap();
    assert!(!log2.contains("\"llm.call\""), "llm must come from the trace: {log2}");
    let tools = log2.lines().filter(|l| l.contains("\"tool.call\"")).count();
    assert_eq!(tools, 3, "tools run live in hybrid mode: {log2}");
}

#[test]
fn full_replay_mocks_tools_from_the_trace() {
    let Some(e) = e2e("fullmock") else { return };
    let py = gen(include_str!("../../../../examples/research_agent.ndg"));
    let out_py = e.dir.join("research_agent.py");
    std::fs::write(&out_py, py).unwrap();
    let driver = e.dir.join("drive_f.py");
    std::fs::write(
        &driver,
        format!("import sys, json\nsys.path.insert(0, {:?})\nimport research_agent as r\nprint(json.dumps(r.run(\"urban heat islands\"), sort_keys=True))\n", e.dir.to_string_lossy()),
    )
    .unwrap();
    let t1 = e.dir.join("t1.jsonl");
    let out1 = run_py(&e, &driver, &[("NUDGE_TRACE", t1.to_str().unwrap())]);
    assert!(out1.status.success(), "stderr: {}", String::from_utf8_lossy(&out1.stderr));
    // full replay (default mode): nothing executes, nothing new is recorded
    let t2 = e.dir.join("t2.jsonl");
    let out2 = run_py(
        &e,
        &driver,
        &[("NUDGE_TRACE", t2.to_str().unwrap()), ("NUDGE_REPLAY", t1.to_str().unwrap())],
    );
    assert!(out2.status.success(), "stderr: {}", String::from_utf8_lossy(&out2.stderr));
    assert_eq!(out1.stdout, out2.stdout);
    let log2 = std::fs::read_to_string(&t2).unwrap_or_default();
    assert!(!log2.contains("\"llm.call\"") && !log2.contains("\"tool.call\""), "full replay must not execute anything: {log2}");
}

// ── v0.2: streaming (design §4.5) ──────────────────────────────

#[test]
fn stream_let_runs_and_traces_chunks() {
    let Some(e) = e2e("streamrun") else { return };
    let src = "type T = { title: string }\nfn main() -> T uses LLM {\n    stream let t: T = llm\"\"\"give me a title\"\"\" with { schema: T, model: \"m\" }\n    t\n}";
    let out_py = e.dir.join("stream_demo.py");
    std::fs::write(&out_py, gen(src)).unwrap();
    let output = run_py(&e, &out_py, &[]);
    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    assert!(String::from_utf8_lossy(&output.stdout).contains("title"), "stdout: {output:?}");
    let log = std::fs::read_to_string(e.dir.join("trace.jsonl")).unwrap();
    assert!(log.contains("\"streamed\": true"), "trace: {log}");
    let chunks: u64 = log
        .lines()
        .filter_map(|l| l.split("\"chunks\": ").nth(1)?.split('}').next()?.trim().parse::<u64>().ok())
        .sum();
    assert!(chunks >= 2, "a 16-char payload should stream in >= 2 chunks, trace: {log}");
}

#[test]
fn stream_aborts_early_on_unsatisfiable_prefix_then_repairs() {
    let Some(e) = e2e("streamabort") else { return };
    // schema expects a string; the fake failure value is an object, so the
    // very first chunk already violates the schema -> early abort (chunk 1)
    let src = "fn main() -> string uses LLM {\n    stream let t: string = llm\"\"\"x\"\"\" with { schema: string, model: \"m\", retry: 2 with repair }\n    t\n}";
    let out_py = e.dir.join("stream_abort.py");
    std::fs::write(&out_py, gen(src)).unwrap();
    let output = run_py(&e, &out_py, &[("NUDGE_FAKE_FAIL_FIRST", "1")]);
    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    let log = std::fs::read_to_string(e.dir.join("trace.jsonl")).unwrap();
    assert!(log.contains("\"early_abort\": true"), "trace: {log}");
    assert!(log.contains("\"outcome\": \"schema_violation\""), "trace: {log}");
    assert!(log.contains("\"repair_round\": 1"), "trace: {log}");
    // the abort happened on the first chunk — tokens beyond it were saved
    let first = log.lines().next().unwrap();
    assert!(first.contains("\"chunks\": 1"), "expected abort on chunk 1, record: {first}");
}

#[test]
fn stream_replay_consumes_the_recorded_value() {
    let Some(e) = e2e("streamreplay") else { return };
    let src = "type T = { title: string }\nfn main() -> T uses LLM {\n    stream let t: T = llm\"\"\"give me a title\"\"\" with { schema: T, model: \"m\" }\n    t\n}";
    let out_py = e.dir.join("stream_replay.py");
    std::fs::write(&out_py, gen(src)).unwrap();
    // 1. live streamed run
    let t1 = e.dir.join("t1.jsonl");
    let out1 = run_py(&e, &out_py, &[("NUDGE_TRACE", t1.to_str().unwrap())]);
    assert!(out1.status.success(), "stderr: {}", String::from_utf8_lossy(&out1.stderr));
    assert!(std::fs::read_to_string(&t1).unwrap().contains("\"streamed\": true"));
    // 2. replay: consumes the recorded final value, no streaming, no new records
    let t2 = e.dir.join("t2.jsonl");
    let out2 = run_py(&e, &out_py, &[("NUDGE_TRACE", t2.to_str().unwrap()), ("NUDGE_REPLAY", t1.to_str().unwrap())]);
    assert!(out2.status.success(), "stderr: {}", String::from_utf8_lossy(&out2.stderr));
    assert_eq!(out1.stdout, out2.stdout, "replay must reproduce the streamed result");
    let log2 = std::fs::read_to_string(&t2).unwrap_or_default();
    assert!(!log2.contains("\"llm.call\""), "replay must not call any provider: {log2}");
}

// ── v0.2: agent state + checkpoints (design §7) ────────────────

#[test]
fn agent_state_checkpoints_each_write() {
    let Some(e) = e2e("agentstate") else { return };
    let src = "agent A {\n    state {\n        notes: [string] = [],\n        round: int = 0,\n    }\n    fn main() -> int uses LLM {\n        let r = llm\"\"\"note\"\"\" with { model: \"m\" }\n        state.notes += [r]\n        state.round += 1\n        state.round\n    }\n}";
    let out_py = e.dir.join("agent_demo.py");
    std::fs::write(&out_py, gen(src)).unwrap();
    let output = run_py(&e, &out_py, &[("NUDGE_RUN_ID", "run-agent-1")]);
    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    assert_eq!(String::from_utf8_lossy(&output.stdout).trim(), "1");
    // every state write checkpointed: round reached 1, notes holds the note
    let ck = std::fs::read_to_string(e.dir.join(".nudge/runs/run-agent-1/checkpoint.json")).unwrap();
    assert!(ck.contains("\"round\": 1"), "checkpoint: {ck}");
    assert!(ck.contains("\"notes\": ["), "checkpoint: {ck}");
    assert!(ck.contains("\"writes\": 2"), "checkpoint: {ck}");
    // the run registry lets `nudge resume` find the program + trace
    let program = std::fs::read_to_string(e.dir.join(".nudge/runs/run-agent-1/program")).unwrap();
    assert!(program.ends_with("agent_demo.py"), "program registry: {program}");
}

#[test]
fn resume_continues_from_checkpoint_without_double_apply() {
    let Some(e) = e2e("resume") else { return };
    // two llm calls with a state write after each; a budget wall after
    // the first call kills the run mid-way
    let src = "agent A {\n    state {\n        round: int = 0,\n    }\n    fn main() -> string uses LLM {\n        let a = llm\"\"\"first\"\"\" with { model: \"m\" }\n        state.round += 1\n        let b = llm\"\"\"second\"\"\" with { model: \"m\" }\n        state.round += 1\n        b\n    }\n}";
    let out_py = e.dir.join("resume_demo.py");
    std::fs::write(&out_py, gen(src)).unwrap();
    // 1. crash: $0.0015 covers exactly one fake call; the second hits the wall
    let trace = e.dir.join("trace.jsonl");
    let out1 = run_py(&e, &out_py, &[("NUDGE_RUN_ID", "run-resume-1"), ("NUDGE_BUDGET", "0.0015")]);
    assert!(!out1.status.success(), "expected a BudgetExceeded crash");
    assert!(String::from_utf8_lossy(&out1.stderr).contains("BudgetExceeded"), "stderr: {}", String::from_utf8_lossy(&out1.stderr));
    let ck = std::fs::read_to_string(e.dir.join(".nudge/runs/run-resume-1/checkpoint.json")).unwrap();
    assert!(ck.contains("\"round\": 1"), "checkpoint after crash: {ck}");
    // 2. resume: replay the recorded call, then go live — round must end
    //    at exactly 2 (the replayed write is suppressed, not re-applied)
    let out2 = run_py(
        &e,
        &out_py,
        &[("NUDGE_RUN_ID", "run-resume-1"), ("NUDGE_REPLAY", trace.to_str().unwrap()), ("NUDGE_RESUME", "1")],
    );
    assert!(out2.status.success(), "resume stderr: {}", String::from_utf8_lossy(&out2.stderr));
    let ck2 = std::fs::read_to_string(e.dir.join(".nudge/runs/run-resume-1/checkpoint.json")).unwrap();
    assert!(ck2.contains("\"round\": 2"), "checkpoint after resume: {ck2}");
    assert!(ck2.contains("\"writes\": 2"), "write counter after resume: {ck2}");
    // the resumed run's live call appended to the same trace: 1 recorded + 1 live
    let log = std::fs::read_to_string(&trace).unwrap();
    let calls = log.lines().filter(|l| l.contains("\"llm.call\"")).count();
    assert_eq!(calls, 2, "expected one recorded + one live call, trace: {log}");
}

// ── v0.3: merge reducer (design §7) ────────────────────────────

#[test]
fn merge_reducer_write_dedups_and_checkpoints() {
    let Some(e) = e2e("merge") else { return };
    // the fake provider returns the same deterministic value for both
    // calls, so the merge reducer keeps exactly one copy
    let src = "type F = { claim: string }\nagent A {\n    state {\n        found: [F] = [],\n    }\n    fn main() -> int uses LLM {\n        let a = llm\"\"\"c\"\"\" with { schema: F, model: \"m\" }\n        state.found = state.found | merge [a]\n        let b = llm\"\"\"c\"\"\" with { schema: F, model: \"m\" }\n        state.found = state.found | merge [b]\n        len(state.found)\n    }\n}";
    let out_py = e.dir.join("merge_demo.py");
    std::fs::write(&out_py, gen(src)).unwrap();
    let output = run_py(&e, &out_py, &[("NUDGE_RUN_ID", "run-merge-1")]);
    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    assert_eq!(String::from_utf8_lossy(&output.stdout).trim(), "1", "merge must dedup the identical findings");
    let ck = std::fs::read_to_string(e.dir.join(".nudge/runs/run-merge-1/checkpoint.json")).unwrap();
    assert!(ck.contains("\"found\": ["), "checkpoint: {ck}");
}

#[test]
fn merge_runtime_semantics() {
    let Some(e) = e2e("mergert") else { return };
    let driver = e.dir.join("drive_merge.py");
    std::fs::write(
        &driver,
        "import nudge_runtime as rt\n# dicts union, right wins\nassert rt.merge({\"a\": 1, \"b\": 1}, {\"b\": 2, \"c\": 3}) == {\"a\": 1, \"b\": 2, \"c\": 3}\n# lists append-dedup\nassert rt.merge([1, 2], [2, 3]) == [1, 2, 3]\nassert rt.merge([], [{\"x\": 1}, {\"x\": 1}]) == [{\"x\": 1}]\n# scalars: right overwrites\nassert rt.merge(1, 2) == 2\nprint(\"MERGE OK\")\n",
    )
    .unwrap();
    let output = run_py(&e, &driver, &[]);
    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    assert!(String::from_utf8_lossy(&output.stdout).contains("MERGE OK"));
}

// ── v0.3b: multi-server MCP routing (design §8) ────────────────────

#[test]
fn tool_stub_routes_and_validates_servers() {
    let Some(e) = e2e("mcpreg") else { return };
    let src = "tool web_search(q: string) -> [string] { impl: mcp(\"search\").web(q) side_effects: none }\nfn main() -> [string] uses Tool {\n    web_search(\"nudge\")\n}";
    let out_py = e.dir.join("mcp_demo.py");
    std::fs::write(&out_py, gen(src)).unwrap();
    // registered server: the call routes and the trace records it
    let output = run_py(&e, &out_py, &[("NUDGE_MCP_SERVERS", "{\"search\": {\"tools\": [\"web_search\"]}, \"fs\": {\"tools\": [\"read\"]}}")]);
    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    let log = std::fs::read_to_string(e.dir.join("trace.jsonl")).unwrap();
    assert!(log.contains("\"server\": \"search\""), "trace: {log}");
    // unregistered server: fails fast with a clear error
    let output2 = run_py(&e, &out_py, &[("NUDGE_MCP_SERVERS", "{\"other\": {}}")]);
    assert!(!output2.status.success(), "expected unknown-server failure");
    assert!(String::from_utf8_lossy(&output2.stderr).contains("unknown MCP server 'search'"), "stderr: {}", String::from_utf8_lossy(&output2.stderr));
}

// ── v0.3d: OTel span export (design §6) ────────────────────────────

#[test]
fn otel_export_writes_spans_for_trace_records() {
    let Some(e) = e2e("otel") else { return };
    let src = "fn main() -> string uses LLM {\n    llm\"\"\"hi\"\"\" with { model: \"m\" }\n}";
    let out_py = e.dir.join("otel_demo.py");
    std::fs::write(&out_py, gen(src)).unwrap();
    let spans = e.dir.join("spans.jsonl");
    let output = run_py(&e, &out_py, &[("NUDGE_OTEL", spans.to_str().unwrap())]);
    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    let log = std::fs::read_to_string(&spans).unwrap();
    let lines: Vec<&str> = log.lines().collect();
    // one span per trace record: llm.call + the effectful fn's fn.return
    assert_eq!(lines.len(), 2, "one span per trace record: {log}");
    let span = lines[0];
    assert!(span.contains("\"name\": \"llm.call\""), "span: {span}");
    assert!(span.contains("\"traceId\"") && span.contains("\"spanId\""), "span: {span}");
    assert!(span.contains("\"startTimeUnixNano\""), "span: {span}");
    assert!(span.contains("\"code\": 1"), "ok status: {span}");
    assert!(lines[1].contains("\"name\": \"fn.return\""), "span: {}", lines[1]);
    // without NUDGE_OTEL no new spans are produced
    let output2 = run_py(&e, &out_py, &[]);
    assert!(output2.status.success());
    assert_eq!(std::fs::read_to_string(&spans).unwrap().lines().count(), 2, "no new spans without NUDGE_OTEL");
}

// ── v0.4: route{} model routing (design §4.4) ─────────────────────

#[test]
fn route_block_picks_model_and_records_label_e2e() {
    let Some(e) = e2e("route") else { return };
    let src = "fn pick(flag: bool) -> string uses LLM {\n    llm\"\"\"hi\"\"\" with { model: route{ cheap: \"m-cheap\" when flag, strong: \"m-strong\" otherwise } }\n}\nfn main() -> string uses LLM {\n    pick(true)\n}";
    let out_py = e.dir.join("route_demo.py");
    std::fs::write(&out_py, gen(src)).unwrap();
    let output = run_py(&e, &out_py, &[]);
    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    let log = std::fs::read_to_string(e.dir.join("trace.jsonl")).unwrap();
    // the when-condition is true → cheap arm wins, model + label recorded
    assert!(log.contains("\"model\": \"m-cheap\""), "trace: {log}");
    assert!(log.contains("\"route\": \"cheap\""), "trace: {log}");
    // flag false → otherwise arm
    let src2 = src.replace("pick(true)", "pick(false)");
    std::fs::write(&out_py, gen(&src2)).unwrap();
    let output2 = run_py(&e, &out_py, &[]);
    assert!(output2.status.success(), "stderr: {}", String::from_utf8_lossy(&output2.stderr));
    let log2 = std::fs::read_to_string(e.dir.join("trace.jsonl")).unwrap();
    assert!(log2.contains("\"model\": \"m-strong\""), "trace: {log2}");
    assert!(log2.contains("\"route\": \"strong\""), "trace: {log2}");
}

// ── v1.1a: real provider adapter (design §4.6) ─────────────────────

#[test]
fn openai_compatible_provider_e2e_with_mock_server() {
    let Some(e) = e2e("openai_provider") else { return };
    // mock OpenAI-compatible endpoint: asserts auth + model, answers with
    // canned JSON and real-shaped usage numbers
    let mock = r#"import json, http.server, socketserver, sys, pathlib

class H(http.server.BaseHTTPRequestHandler):
    def do_POST(self):
        n = int(self.headers.get("Content-Length", 0))
        body = json.loads(self.rfile.read(n) or b"{}")
        assert self.path == "/v1/chat/completions", self.path
        assert body["model"] == "gemini-2.5-flash", body
        assert self.headers.get("Authorization") == "Bearer test-key", "missing auth"
        resp = {"choices": [{"message": {"content": "{\"title\": \"ok\", \"confidence\": 0.9}"}}],
                "usage": {"prompt_tokens": 12, "completion_tokens": 7}}
        data = json.dumps(resp).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)
    def log_message(self, *a):
        pass

with socketserver.TCPServer(("127.0.0.1", 0), H) as srv:
    pathlib.Path(sys.argv[1]).write_text(str(srv.server_address[1]))
    srv.handle_request()
"#;
    std::fs::write(e.dir.join("mock.py"), mock).unwrap();
    let port_file = e.dir.join("port.txt");
    let mut child = std::process::Command::new("python3")
        .arg(e.dir.join("mock.py"))
        .arg(&port_file)
        .spawn()
        .expect("spawn mock server");
    let mut port = String::new();
    for _ in 0..100 {
        if let Ok(p) = std::fs::read_to_string(&port_file) {
            if !p.trim().is_empty() {
                port = p.trim().to_string();
                break;
            }
        }
        std::thread::sleep(std::time::Duration::from_millis(100));
    }
    assert!(!port.is_empty(), "mock server did not start");

    // a gemini-prefixed model routes through the OpenAI-compatible adapter;
    // the JSON answer is extracted and validated against the schema
    let src = "type Smoke = { title: string, confidence: float }\nfn main() -> string uses LLM {\n    let a = llm\"\"\"give json\"\"\" with { model: \"gemini:gemini-2.5-flash\", schema: Smoke, budget: 0.05 USD }\n    a.title\n}";
    let out_py = e.dir.join("openai_provider.py");
    std::fs::write(&out_py, gen(src)).unwrap();
    let base = format!("http://127.0.0.1:{port}/v1");
    let output = run_py(&e, &out_py, &[("NUDGE_API_KEY", "test-key"), ("NUDGE_BASE_URL", base.as_str())]);
    let _ = child.kill();
    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    let log = std::fs::read_to_string(e.dir.join("trace.jsonl")).unwrap();
    assert!(log.contains("\"provider\": \"gemini\""), "trace: {log}");
    assert!(log.contains("\"model\": \"gemini:gemini-2.5-flash\""), "trace: {log}");
    assert!(log.contains("\"tokens\": {\"in\": 12, \"out\": 7}"), "trace: {log}");
    // (12 in * $0.30 + 7 out * $2.50) / 1M from the pricing table
    assert!(log.contains("\"cost_usd\": 2.11e-05"), "trace: {log}");
}
